### ISSUE TITLE
wrong type of `authenticator_uid` in the documentation and not supported by `ansible.platform.user` 2.5.3 (latest version)

### ISSUE THREAD

**Issue by ivarmu** [redhat-cop/automate_tower_genie_collections#1010]
The parameter `authenticator_uid` defined below is told to be a boolean, but this should be a String:

https://github.com/redhat-cop/infra.aap_configuration/blob/c15dc5d80c7f285023e2c2a5cfc0c20f4466a260/roles/gateway_users/README.md?plain=1#L64

The extracted information from the API is like follows:

```yaml
---
aap_user_accounts:
  - username: "admin"
    password: "INITIAL"
    email: "admin@example.com"
    first_name: ""
    last_name: ""
    is_superuser: "True"
    authenticators: [1]
    authenticator_uid: "admin"
```

The parameter `authenticator_uid` seems to not be supported by the `ansible.platform` collection (version 2.5.3), causing the following error:

```
"msg": "Unsupported parameters for (ansible.platform.user) module: authenticator_uid. Supported parameters include: authenticator_users, authenticators, email, first_name, gateway_hostname, gateway_password, gateway_request_timeout, gateway_token, gateway_username, gateway_validate_certs, is_superuser, last_name, organizations, password, state, update_secrets, username (request_timeout, superuser, validate_certs).",
```
