### ISSUE TITLE
POC: Add role attachment option to each role

### ISSUE THREAD

**Issue by Tompage1994** [redhat-cop/automate_tower_genie_collections#1040]
**Is your feature request related to a problem? Please describe.**
Add a role binding option to each role to attach teams/user permissions.
This is an idea which we can POC first to see what it looks like.

**Describe the solution you'd like**
Ideally the variable structure should be simple and be added to e.g controller_job_templates:

```
controller_job_templates:
  name: Demo Job Template
  playbook: hello_world.yml
  project: Demo Project
  roles:
    execute:
      teams:
        - myorg_executors
```

(Note, the above is an example and may not be the final structure)

**Describe alternatives you've considered**
N/A this is a technical spike to test out the solution

**Additional context**
Discussed in the community meeting 06/03/2025
