### ISSUE TITLE
Empty values of controller objects when deleting them from the config file

### ISSUE THREAD

**Issue by ShawkatAbuElnaser** [redhat-cop/automate_tower_genie_collections#1047]
**Is your feature request related to a problem? Please describe.**
Currently the infra.aap_configuration collection does not support deleting values from the automation controller objects when attributes are deleted or assigned an empty list from the configuration YAML. So for example when instance groups were specified for a job template in the configuration YAML and then later get deleted, they dont automatically get deleted in the AAP.

**Describe the solution you'd like**
The values or attributes of the automation controller objects (for example job templates) should be deleted by simply deleting them in the configuration YAML or assigning them to an empty list/string.

**Comment by Tompage1994** [comment]
Hi @ShawkatAbuElnaser 

I'm not 100% sure what you mean by your request, but I have narrowed it down to two options:

1. You want the options of a single JT (or other object) to be set the the default (often empty) value when left out. e.g.
```
controller_templates:
  - name: my_template
    description: test template
    project: my_project
    inventory: my_inv
    playbook: hello_world.yml
    # limit: linux  # You've decided to remove this item so want it to revert to blank
```
In this case, if you set `aap_configuration_enforce_defaults: true` the default value will be applied to the item. For limit this is `''`. If you only want to do this for job_templates, you can also just use `controller_configuration_job_templates_enforce_defaults: true` which applied just to the job_templates role.

2. You want a JT to be removed if you remove it from the list.
If this is the case of what you want to achieve, this functionality does exist, but not within this collection. Check out the `infra.aap_configuration_extended.object_diff` role [here](https://github.com/redhat-cop/aap_configuration_extended/tree/devel/roles/object_diff).

I'm going to close this issue because I believe I've answered what you need, but if I haven't, please do reopen it and give me a specific (ideally with a code snippet) example of what you expect to be able to achieve.

Thanks
