### ISSUE TITLE
controller_projects: "msg": "the field 'tags' should be a list

### ISSUE THREAD

**Issue by ikke-t** [redhat-cop/automate_tower_genie_collections#1051]
## Summary

Creating projects fail.

## Issue Type

- Bug Report

## Ansible, Collection, Controller details

```console (paste below)
ansible [core 2.14.17]
  config file = /var/home/itengval/src/redhatnordicssa/cool-lab/ansible.cfg
  configured module search path = ['/var/home/itengval/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /var/home/itengval/.ansible/collections:/usr/share/ansible/collections
  executable location = /var/home/itengval/.local/bin/ansible
  python version = 3.9.21 (main, Dec  5 2024, 00:00:00) [GCC 11.5.0 20240719 (Red Hat 11.5.0-2)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True


╰─➤ ansible-galaxy collection list -p collections


# /var/home/itengval/src/redhatnordicssa/cool-lab/collections/ansible_collections
Collection                  Version     
--------------------------- ------------
amazon.aws                  9.3.0       
ansible.controller          4.6.8       
ansible.eda                 2.6.0       
ansible.hub                 1.0.0       
ansible.platform            2.5.20250213
ansible.posix               2.0.0       
awx.awx                     24.6.1      
cloud.common                4.0.0       
community.crypto            2.25.0      
community.general           10.4.0      
community.vmware            5.4.0       
containers.podman           1.16.3      
dynatrace.oneagent          1.2.3       
infra.aap_configuration     3.1.0       
kubernetes.core             5.1.0       
microsoft.sql               2.5.2       
myllynen.ansible_packer     2.0.4       
myllynen.rhel_ansible_roles 2.0.4       
myllynen.rhel_image         1.3.3       
redhat.rhel_idm             1.14.5      
redhat.rhel_system_roles    1.88.9      
redhat.satellite            5.1.0       
redhat.satellite_operations 3.0.0       
vmware.vmware               1.10.1      
vmware.vmware_rest          4.6.0       

# /var/home/itengval/.ansible/collections/ansible_collections
Collection           Version
-------------------- -------
community.general    10.1.0 
community.kubernetes 2.0.1  
kubernetes.core      2.3.0

Controller version

Ansible Automation Platform 2.5

Automation Controller Version
    4.6.9
Event Driven Automation Version
    1.1.6
Automation Hub Version
    4.10.2
```

- ansible installation method: one of source, pip, OS package, EE
ansible-core-2.14.17-1.el9.x86_64

## OS / ENVIRONMENT

rhel9 container. Also in F41 container the same result

## Desired Behavior

Add the project listed 

## Actual Behavior

╰─➤ ansible-playbook -i localhost, -e @../private-lab/secrets.yml aap_configure.yml

with this config:
```
controller_projects:
  - name: Cool-Lab
    description: Red Hat Nordics SA Cool Lab project
    organization: Red Hat
    scm_type: git
    scm_url: https://github.com/RedHatNordicsSA/cool-lab.git
    scm_branch: arrowlab
    scm_clean: true
    scm_update_on_launch: false
    wait: true
    update_project: true
```

Fails with:

```console (error)
TASK [infra.aap_configuration.controller_projects : Validating arguments against arg spec 'main' - An Ansible Role to create projects on Ansible Controller.] *****
Friday 21 March 2025  15:18:18 +0200 (0:00:01.581)       0:00:37.556 ********** 
fatal: [localhost]: FAILED! => {"msg": "the field 'tags' should be a list of ((<class 'str'>,), <class 'int'>), but the item '['inventories', 'projects']' is a <cl
ass 'list'>"}

PLAY RECAP 
localhost                  : ok=36   changed=3    unreachable=0    failed=1    skipped=7    rescued=0    ignored=0   
```

## STEPS TO REPRODUCE

Installed AAP on OCP with operator using all defaults.
Create vars file with the above.
and run it with the playbook: https://github.com/RedHatNordicsSA/cool-lab/blob/arrowlab/aap_configure.yml
╰─➤ ansible-playbook -i localhost, -e @../private-lab/secrets.yml aap_configure.yml

**Comment by djdanielsson** [comment]
can you try again with the latest release and see if you still have this issue

**Comment by RichardWardle** [comment]
I hit this also still on the latest version:

```❯ ansible-galaxy collection list infra.aap_configuration

# /Users/REDACTED/Documents/repos/au-ansible-cm-aap/collections/ansible_collections
Collection              Version
----------------------- -------
infra.aap_configuration 3.2.0
```

When running we see:

```TASK [infra.aap_configuration.gateway_organizations : Managing Controller Organizations | Wait for finish the Organizations management] ***
skipping: [localhost]

TASK [infra.aap_configuration.controller_projects : Validating arguments against arg spec 'main' - An Ansible Role to create projects on Ansible Controller.] ***
fatal: [localhost]: FAILED! => {"msg": "the field 'tags' should be a list of ((<class 'str'>,), <class 'int'>), but the item '['inventories', 'projects']' is a <class 'list'>"}

PLAY RECAP ***********************************************************************************************************************
localhost                  : ok=136  changed=3    unreachable=0    failed=1    skipped=65   rescued=0    ignored=0   
```

We were seeing this even when we commented out the controller_projects (example snip of the yaml below):

```---
controller_projects:
  - name: VMware
    description: Vmware Configuration Management
    organization: org_nutrien_ids
    scm_branch: "{{ github_branch }}"
    scm_type: git
    credential: Git
    default_environment: Windows Execution Environment
    scm_url: https://github.com/REDACTED
```

To work around it we did the below in controller_configuration_dispatcher_roles (set in the defaults/main.yml in the dispatch role where ever the tags var was set as a list:

```      - role: controller_projects
        var: controller_projects
        tags: projects # << ADD this
        # tags: << comment out
        #   - inventories
        #   - projects
```

**Comment by sean-m-sullivan** [comment]
@RichardWardle I am not seeing this issue, Used the following playbook
```
---
- name: Playbook to configure ansible controller post installation
  hosts: localhost
  connection: local
  vars:
    controller_projects:
      - name: Config
        organization: Default
        scm_branch: devel
        scm_type: git
        scm_url: https://github.com/redhat-cop/infra.aap_configuration/
    aap_hostname: homelabaap.homelab.com
    aap_username: admin
    aap_password: password123!
    aap_validate_certs: false
  tasks:

    - name: Call dispatch role
      ansible.builtin.include_role:
        name: infra.aap_configuration.dispatch
...
```

What version of aap_configuration are you using. 

I tested with 
ansible.controller:4.6.11 and devel.
