### ISSUE TITLE
infra.aap_configuration.controller_license fails with username and password

### ISSUE THREAD

**Issue by ikke-t** [redhat-cop/automate_tower_genie_collections#1068]
## Summary

I want to subscribe my AAP using user credentials, but it fails to unknown variable while running it.

## Issue Type

- Bug Report

## Ansible, Collection, Controller details

```console
ansible [core 2.18.1]
  config file = /var/home/itengval/src/redhatnordicssa/cool-lab/ansible.cfg
  configured module search path = ['/var/home/itengval/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /var/home/itengval/.local/lib/python3.13/site-packages/ansible
  ansible collection location = /var/home/itengval/.ansible/collections:/usr/share/ansible/collections
  executable location = /var/home/itengval/.local/bin/ansible
  python version = 3.13.2 (main, Feb  6 2025, 00:00:00) [GCC 15.0.1 20250204 (Red Hat 15.0.1-0)] (/usr/bin/python3)
  jinja version = 3.1.5
  libyaml = True


# /var/home/itengval/.ansible/collections/ansible_collections
Collection                       Version     
-------------------------------- ------------
community.general                10.1.0      
community.kubernetes             2.0.1       
kubernetes.core                  2.3.0       

# /var/home/itengval/src/redhatnordicssa/cool-lab/collections/ansible_collections
Collection                       Version     
-------------------------------- ------------
amazon.aws                       9.3.0       
ansible.controller               4.6.8       
ansible.eda                      2.6.0       
ansible.hub                      1.0.0       
ansible.platform                 2.5.20250213
ansible.posix                    2.0.0       
awx.awx                          24.6.1      
cloud.common                     4.0.0       
community.crypto                 2.25.0      
community.general                10.4.0      
community.vmware                 5.4.0       
containers.podman                1.16.3      
dynatrace.oneagent               1.2.3       
infra.aap_configuration          3.2.0       
infra.aap_configuration_extended 1.0.0       
kubernetes.core                  5.1.0       
microsoft.sql                    2.5.2       
myllynen.ansible_packer          2.1.0       
myllynen.rhel_ansible_roles      2.1.0       
myllynen.rhel_image              1.4.0       
redhat.rhel_idm                  1.14.5      
redhat.rhel_system_roles         1.88.9      
redhat.satellite                 5.1.0       
redhat.satellite_operations      3.0.0       
vmware.vmware                    1.10.1      
vmware.vmware_rest               4.6.0   

Controller version: aap-operator.v2.5.0-0.1743660124
```

- ansible installation method: one of source, pip, OS package, EE

OCP AAP Operator

## OS / ENVIRONMENT

OCP 4.18 + aap-operator.v2.5.0-0.1743660124

## Desired Behavior

set the lisence using credentials.

## Actual Behavior

```console (error)
Friday 25 April 2025  16:43:15 +0300 (0:00:05.905)       0:00:06.389 ********** 
fatal: [localhost]: FAILED! => {
    "msg": "The task includes an option with an undefined variable.. list object has no element 0\n\nThe error appears to be in '/var/home/itengval/src/redhatnordicssa/cool-lab/collections/ansible_collections/infra/aap_configuration/roles/controller_license/tasks/subscription.yml': line 21, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: subscription | Install the Controller license\n  ^ here\n"

```

## STEPS TO REPRODUCE

I set variables:

```
aap_configuration_secure_logging: false
controller_configuration_organizations_secure_logging: false
controller_configuration_credential_types_secure_logging: false
controller_configuration_credentials_secure_logging: false
controller_configuration_execution_environments_secure_logging: false
controller_configuration_projects_secure_logging: false
controller_configuration_inventories_secure_logging: false

redhat_subscription_username: "{{ vault_rh_subs_username }}"
redhat_subscription_password: "{{ vault_rh_subs_password }}"
controller_license:
  use_lookup: true
  filters:
    product_name: "Red Hat Ansible Automation Platform"
    support_level: "Self-Support"
```

And run playbook with the variables:

```
- name: Configure automation hub
  connection: local
  hosts: all
  become: false
  gather_facts: false
  vars:
    aap_username: admin
    aap_password: "{{ vault_aap_admin_password }}"
    aap_validate_certs: false
  vars_files:
    - aap_configs_dir/vars_content.yml
    - aap_configs_dir/vars_creds.yml
    - aap_configs_dir/vars_gw.yml
    - aap_configs_dir/vars_hub.yml
    - aap_configs_dir/vars_license.yml
    - aap_configs_dir/vars_organizations.yml

  roles:
    # Setup license
    - infra.aap_configuration.controller_license 
```

and run the playbook:

``` 
ansible-playbook -i localhost, -e @../private-lab/secrets.yml aap_configure_subset.yml

```

**Comment by djdanielsson** [comment]
I believe this is an issue with the module itself and not with the role

**Comment by sean-m-sullivan** [comment]
Just tested this, it worked, I suspect some variables are not going through or the filter is off and may not match your subscription. What is the output of

TASK [infra.aap_configuration.controller_license : subscription | Get subscriptions with a filter]
```
    "subscriptions": [
        {
            "account_number": "112334351234",
            "instance_count": 16,
            "license_date": 1770353999,
            "license_type": "developer",
            "pool_id": "asdfasdf",
            "product_name": "Red Hat Ansible Automation Platform",
            "satellite": null,
            "sku": "222",
            "subscription_id": "2",
            "subscription_name": "Red Hat Developer Subscription for Individuals",
            "support_level": "Self-Support",
            "usage": "Development/Test",
            "valid_key": true
        },
        {
            "account_number": "112334351234",
            "instance_count": 16,
            "license_date": 1758686399,
            "license_type": "developer",
            "pool_id": "asdfasdf",
            "product_name": "Red Hat Ansible Automation Platform",
            "satellite": null,
            "sku": "222",
            "subscription_id": "2",
            "subscription_name": "Red Hat Developer Subscription for Individuals",
            "support_level": "Self-Support",
            "usage": "Development/Test",
            "valid_key": true
        },
        {
            "account_number": "112334351234",
            "instance_count": 100,
            "license_date": 1751169599,
            "license_type": "trial",
            "pool_id": "asdfasdf",
            "product_name": "Red Hat Ansible Automation Platform",
            "satellite": null,
            "sku": "222",
            "subscription_id": "2",
            "subscription_name": "60 Day Product Trial of Red Hat Ansible Automation Platform, Self-Supported (100 Managed Nodes)",
            "support_level": "Self-Support",
            "trial": true,
            "usage": "",
            "valid_key": true
        },
        {
            "account_number": "112334351234",
            "instance_count": 16,
            "license_date": 1764651599,
            "license_type": "developer",
            "pool_id": "asdfasdf",
            "product_name": "Red Hat Ansible Automation Platform",
            "satellite": null,
            "sku": "222",
            "subscription_id": "2",
            "subscription_name": "Red Hat Developer Subscription for Individuals",
            "support_level": "Self-Support",
            "usage": "Development/Test",
            "valid_key": true
        },
        {
            "account_number": "112334351234",
            "instance_count": 250000,
            "license_date": 1798779599,
            "license_type": "enterprise",
            "pool_id": "asdfasdf",
            "product_name": "Red Hat Ansible Automation Platform",
            "satellite": null,
            "sku": "222",
            "subscription_id": "2",
            "subscription_name": "Employee SKU",
            "support_level": "Self-Support",
            "usage": "Development/Test",
            "valid_key": true
        },
        {
            "account_number": "112334351234",
            "instance_count": 9999999,
            "license_date": 1798779599,
            "license_type": "enterprise",
            "pool_id": "asdfasdf",
            "product_name": "Red Hat Ansible Automation Platform",
            "satellite": null,
            "sku": "222",
            "subscription_id": "2",
            "subscription_name": "Employee SKU",
            "support_level": "Self-Support",
            "usage": "Development/Test",
            "valid_key": true
        }
    ]
}
```

This is the playbook I used
```
---
- name: Playbook to configure ansible controller post installation
  hosts: localhost
  connection: local
  vars:
    controller_projects:
    redhat_subscription_username: asdfasdf
    redhat_subscription_password: asdfasdf
    controller_license:
      use_lookup: true
      filters:
        product_name: "Red Hat Ansible Automation Platform"
        support_level: "Self-Support"
    aap_hostname: aap.asdf.asdf.com
    aap_username: admin
    aap_password: asdf!
    aap_validate_certs: false
  roles:
    # Setup license
    - infra.aap_configuration.controller_license 


...
```

**Comment by ikke-t** [comment]
Mine doesn't get that far. The task fails before it prints out any of such:

```
TASK [infra.aap_configuration.controller_license : subscription | Get subscriptions with a filter] ******************************************************
task path: /var/home/itengval/src/redhatnordicssa/cool-lab/collections/ansible_collections/infra/aap_configuration/roles/controller_license/tasks/subscri
ption.yml:4
Friday 16 May 2025  09:25:26 +0300 (0:00:00.105)       0:00:00.562 ************ 
fatal: [localhost]: FAILED! => {
    "msg": "The conditional check ''use_lookup' in controller_license' failed. The error was: error while evaluating conditional ('use_lookup' in control
ler_license): 'controller_license' is undefined\n\nThe error appears to be in '/var/home/itengval/src/redhatnordicssa/cool-lab/collections/ansible_collec
tions/infra/aap_configuration/roles/controller_license/tasks/subscription.yml': line 4, column 3, but may\nbe elsewhere in the file depending on the exac
t syntax problem.\n\nThe offending line appears to be:\n\n\n- name: subscription | Get subscriptions with a filter\n  ^ here\n"
}
```

**Comment by ikke-t** [comment]
I paste that to echo, and it's easier to read:
```
The conditional check ''use_lookup' in controller_license' failed. The error was: error while evaluating conditional ('use_lookup' in control
ler_license): 'controller_license' is undefined

The error appears to be in '/var/home/itengval/src/redhatnordicssa/cool-lab/collections/ansible_collec
tions/infra/aap_configuration/roles/controller_license/tasks/subscription.yml': line 4, column 3, but may
be elsewhere in the file depending on the exac
t syntax problem.

The offending line appears to be:


- name: subscription | Get subscriptions with a filter
  ^ here

```

**Comment by djdanielsson** [comment]
have you tried pulling the latest version of ansible.controller collection?

**Comment by DLV1810** [comment]
I hit this today, there's been a change on the ansible.controller side

username/password aren't valid - now changed to client_id/client_secret as of ansible.controller 4.6.13

Fix is probably just changing that field, but i'm hitting other problems right now so can't test/validate. Going back to an EE with has an older version of the ansible.controller works.

eg.

```
ee-supported-rhel9:1.0.0-961 - 4.6.11
ee-supported-rhel9:1.0.0-1001 - 4.6.12

```

**Comment by DLV1810** [comment]
Looks like a new service account is required too

Input client ID and client secret or username and password
Ansible subscriptions now require a service account from HCC. You must [create a service account here](https://console.redhat.com/iam/service-accounts) and use the client ID and client secret to replace your username and password when logging in. For Red Hat Satellite, input your username and password in the fields below. Please see this [Knowledgebase article](https://access.redhat.com/articles/7112649) for more information.

**Comment by djdanielsson** [comment]
so this isn't a bug but the documentation on the role needs to be updated to be clear on how to auth correctly, is that correct?

**Comment by ikke-t** [comment]
and my subs

<img width="1057" height="239" alt="Image" src="https://github.com/user-attachments/assets/3335ac29-8eb2-495f-a619-7821d70bbe4f" />

**Comment by ikke-t** [comment]
after I updated ansible -collection, the error changed:
```
fatal: [localhost]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3.13"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "aap_token": null,
            "client_id": null,
            "client_secret": null,
            "controller_config_file": null,
            "controller_host": "aap-aap.apps.mgmt.eu.arrow.lab",
            "controller_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "controller_username": "admin",
            "filters": {
                "product_name": "Red Hat Ansible Automation Platform, Standard (100 Managed Nodes)",
                "support_level": "Standard"
            },
            "password": "xxxx",
            "request_timeout": null,
            "username": "d1d1576e-f6b4-4930-8ceb-e9ad2581455f",
            "validate_certs": false
        }
    },
    "msg": "missing required arguments: client_id, client_secret"
}
```
but no such variables are in documentation for license role

**Comment by myllynen** [comment]
The error message is due to how infra.aap_configuration.controller_license is calling ansible.controller.subscriptions, its document mentions those arguments being required:

https://console.redhat.com/ansible/automation-hub/repo/published/ansible/controller/content/module/subscriptions/

**Comment by ikke-t** [comment]
the collecitons versions as of today, I just updated it:
``` 
# /var/home/itengval/.ansible/collections/ansible_collections
Collection                       Version     
-------------------------------- ------------
community.general                10.1.0      
community.kubernetes             2.0.1       
kubernetes.core                  2.3.0       

# /var/home/itengval/src/redhatnordicssa/cool-lab/collections/ansible_collections
Collection                       Version     
-------------------------------- ------------
amazon.aws                       10.1.1      
ansible.controller               4.6.19      
ansible.eda                      2.10.0      
ansible.hub                      1.0.2       
ansible.platform                 2.5.20250702
ansible.posix                    2.1.0       
awx.awx                          24.6.1      
community.crypto                 3.0.3       
community.vmware                 6.0.0       
containers.podman                1.18.0      
dynatrace.oneagent               1.2.4       
fedora.linux_system_roles        1.109.0     
infra.aap_configuration          3.7.0       
infra.aap_configuration_extended 3.0.1       
infra.ee_utilities               4.0.4       
kubernetes.core                  6.1.0       
microsoft.sql                    2.6.4       
myllynen.ansible_packer          2.3.1       
myllynen.rhel_ansible_roles      3.2.6       
myllynen.rhel_image              2.1.0       
redhat.openshift                 5.0.0       
redhat.openshift_virtualization  2.2.3       
redhat.rhel_idm                  1.15.1      
redhat.rhel_system_roles         1.95.7      
redhat.satellite                 5.6.0       
redhat.satellite_operations      3.0.0       
vmware.vmware                    2.3.0       
vmware.vmware_rest               4.9.0       
```

**Comment by ikke-t** [comment]
I changed the subscriptions task to have the client id and secret:
```
- name: subscription | Get subscriptions with a filter
  ansible.controller.subscriptions:
    client_id: "{{ redhat_subscription_username }}"
    client_secret: "{{ redhat_subscription_password }}"
    filters: "{{ controller_license.filters | default(_redhat_cop_license_filters) }}"
    # Role Standard Options
    controller_host: "{{ aap_hostname | default(omit, true) }}"
    controller_username: "{{ aap_username | default(omit, true) }}"
    controller_password: "{{ aap_password | default(omit, true) }}"
    controller_oauthtoken: "{{ aap_token | default(omit, true) }}"
    request_timeout: "{{ aap_request_timeout | default(omit, true) }}"
    validate_certs: "{{ aap_validate_certs | default(omit) }}"
  register: subscription
  when:
    - "'use_lookup' in controller_license"
    - controller_license.use_lookup
```

and now it fails again with str error:

```
The full traceback is:
Traceback (most recent call last):
  File "/var/home/itengval/.ansible/tmp/ansible-tmp-1758886019.9955618-191584-222548079666990/AnsiballZ_subscriptions.py", line 107, in <module>
    _ansiballz_main()
    ~~~~~~~~~~~~~~~^^
  File "/var/home/itengval/.ansible/tmp/ansible-tmp-1758886019.9955618-191584-222548079666990/AnsiballZ_subscriptions.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/itengval/.ansible/tmp/ansible-tmp-1758886019.9955618-191584-222548079666990/AnsiballZ_subscriptions.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.ansible.controller.plugins.modules.subscriptions', init_globals=dict(_module_fqn='ansible_collections.ansible.controller.plugins.modules.subscriptions', _modlib_path=modlib_path),
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                     run_name='__main__', alter_sys=True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen runpy>", line 226, in run_module
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/tmp/ansible_ansible.controller.subscriptions_payload_vnijizgu/ansible_ansible.controller.subscriptions_payload.zip/ansible_collections/ansible/controller/plugins/modules/subscriptions.py", line 102, in <module>
  File "/tmp/ansible_ansible.controller.subscriptions_payload_vnijizgu/ansible_ansible.controller.subscriptions_payload.zip/ansible_collections/ansible/controller/plugins/modules/subscriptions.py", line 93, in main
AttributeError: 'str' object has no attribute 'get'
[WARNING]: Platform linux on host localhost is using the discovered Python interpreter at /usr/bin/python3.13, but future installation of another Python interpreter could change the meaning of that
path. See https://docs.ansible.com/ansible-core/2.18/reference_appendices/interpreter_discovery.html for more information.
fatal: [localhost]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3.13"
    },
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/var/home/itengval/.ansible/tmp/ansible-tmp-1758886019.9955618-191584-222548079666990/AnsiballZ_subscriptions.py\", line 107, in <module>\n    _ansiballz_main()\n    ~~~~~~~~~~~~~~~^^\n  File \"/var/home/itengval/.ansible/tmp/ansible-tmp-1758886019.9955618-191584-222548079666990/AnsiballZ_subscriptions.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/home/itengval/.ansible/tmp/ansible-tmp-1758886019.9955618-191584-222548079666990/AnsiballZ_subscriptions.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.ansible.controller.plugins.modules.subscriptions', init_globals=dict(_module_fqn='ansible_collections.ansible.controller.plugins.modules.subscriptions', _modlib_path=modlib_path),\n    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n                     run_name='__main__', alter_sys=True)\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"<frozen runpy>\", line 226, in run_module\n  File \"<frozen runpy>\", line 98, in _run_module_code\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/tmp/ansible_ansible.controller.subscriptions_payload_vnijizgu/ansible_ansible.controller.subscriptions_payload.zip/ansible_collections/ansible/controller/plugins/modules/subscriptions.py\", line 102, in <module>\n  File \"/tmp/ansible_ansible.controller.subscriptions_payload_vnijizgu/ansible_ansible.controller.subscriptions_payload.zip/ansible_collections/ansible/controller/plugins/modules/subscriptions.py\", line 93, in main\nAttributeError: 'str' object has no attribute 'get'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE: No start of json char found\nSee stdout/stderr for the exact error",
    "rc": 1
}

```
