### ISSUE TITLE
Authentication Maps documentation is misleading

### ISSUE THREAD

**Issue by acomathes** [redhat-cop/automate_tower_genie_collections#1078]
## Summary

This is from the documentation page for `gateway_authenticator_maps` (05/08/2025):

```
---
gateway_authenticator_maps:
- name: AuthMap 1
  authenticator: Auth 1
  revoke: true
  map_type: organization
  organization: Organization 1
  role: Organization Admin
  triggers:
    always: { }
    never: { }
    groups:
      has_or:
      - has_or_11
      - has_or_22
      has_and:
      - has_and_1
      - has_and_22
    attributes:
      join_condition: "or"
      attr_1:
        contains: aaa
        matches: "bbb"
        ends_with: "ccc"
      attr_2:
        in:
        - abc1
        - abc2
        - abc3
```

However, when I want to create an authentication mapping with a groups trigger, having `always: { }` and/or `never: {}` will lead the mapping to always skip. And it does not make much sense to have multiple triggers within a single authentication mapping, because AAP 2.5's UI has a 1-1 relation between authentication mappings and their triggers.

Fun fact: on the UI, clicking on edit the authentication method, and not touching anything and saving solves the problem, because the UI DELETEs all authentication mappings and rePOSTs them, and the new authentication mappings and up not having the `always: { }` and/or `never: {}` and has only the `groups:` trigger.

## Issue Type

- Bug Report

## Ansible, Collection, Controller details

Tested on AAP 2.5 with infra.aap_configuration 3.2.0.
