### ISSUE TITLE
Job templates

### ISSUE THREAD

**Issue by tonyreveal** [redhat-cop/automate_tower_genie_collections#113]
There is a documentation error for job templates.

In the table describing the variables the documentation indicates to define the data structure as ` job_templates `.  But in the actual JSON example it's just ` templates `.   And looking at the task it appears you're looking for ` tower_templates `.

**Comment by nleiva** [comment]
We run into this as well. There is a disconnection between the example and the actual task. 

The [task](https://github.com/redhat-cop/tower_configuration/blob/devel/roles/job_templates/tasks/main.yml):

```yaml
# Create Job Template
- name: Add Tower Job Templates
  awx.awx.tower_job_template:
    name:                           "{{ tower_templates_item.name }}"
    ...
  loop: "{{ tower_templates }}"
```

The [example](https://github.com/redhat-cop/tower_configuration/tree/devel/roles/job_templates#standard-role-usage):

```yaml
    - name: Add Projects
      include_role:
        name: redhat_cop.tower_configuration.job_templates
      vars:
        templates: "{{ job_templates_json.templates }}"
```

The example should say:

```yaml
      vars:
        tower_templates: "{{ job_templates_json.templates }}"
```
