### ISSUE TITLE
Importing project from YAML generated by awxkit fails on scm_credential

### ISSUE THREAD

**Issue by ghurel-rh** [redhat-cop/automate_tower_genie_collections#144]
Tested with awxkit 17.0.0

When exporting a project using `awx export --projects `, the generated YAML file is as follows:
```
- allow_override: true
  credential:
    credential_type:
      kind: scm
      name: Source Control
      type: credential_type
    name: git.net-courrier - source control
    organization:
      name: CSM SI
      type: organization
    type: credential
[...]
```

The code in [roles/projects/tasks/main.yml#L11](https://github.com/redhat-cop/tower_configuration/blob/e5e4576f3dfca4966a3468d41fef9ef6ee8ea7d8/roles/projects/tasks/main.yml#L11) to import the project is not able to directly use this YAML and will break with the following error:
```
"msg": "Request to /api/v2/credentials/?name=%7B%27credential_type%27%3A+%7B%27kind%27%3A+%27scm%27%2C+%27name%27%3A+%27Source+Control%27%2C+%27type%27%3A+%27credential_type%27%7D%2C+%27name%27%3A+%27git.net-courrier+-+source+control%27%2C+%27organization%27%3A+%7B%27name%27%3A+%27CSM+SI%27%2C+%27type%27%3A+%27organization%27%7D%2C+%27type%27%3A+%27credential%27%7D returned 0 items, expected 1",
``` 

A very simple fix would be to change line 11 from:
```
"scm_credential:                 "{{ tower_projects_item.scm_credential | default(tower_projects_item.credential | default(omit)) }}""
```
to:
```
"scm_credential:                 "{{ tower_projects_item.scm_credential | default(tower_projects_item.credential.name | default(omit)) }}""
```

Making thus very easy to export/import directly.
