### ISSUE TITLE
Updating a project from YAML generated by awxkit fails on scm_credential

### ISSUE THREAD

**Issue by ghurel-rh** [redhat-cop/automate_tower_genie_collections#148]
Tested with awxkit 17.0.0

(very similar to #144 , but this time for project update).

When exporting a project using awx export --projects , the generated YAML file is as follows:

```
- allow_override: true
  credential:
    credential_type:
      kind: scm
      name: Source Control
      type: credential_type
    name: git.net-courrier - source control
    organization:
      name: CSM SI
      type: organization
    type: credential
[...]
```
The code in [roles/project_update/tasks/main.yml#L6](https://github.com/redhat-cop/tower_configuration/blob/6b76e8bccdeed57e625db4f373ccfb372626405a/roles/project_update/tasks/main.yml#L6) to update the project is not able to directly use this YAML and will break with the following error:

```
"msg": "Request to /api/v2/organizations/?name=%7B%27type%27%3A+%27organization%27%2C+%27name%27%3A+%27CSM+SI%27%7D returned 0 items, expected 1"
```

A very simple fix would be to change line 6 from:
```
organization:       "{{ __project_update_update_item.organization | default(omit, true) }}"
```
to:
```
organization:       "{{ __project_update_update_item.organization.name | default(__project_update_update_item.organization | default(omit, true)) }}"
```

Cheers
