### ISSUE TITLE
Using deprecated field "kind" when importing credentials breaks the import if kind is cloud or external.

### ISSUE THREAD

**Issue by ghurel-rh** [redhat-cop/automate_tower_genie_collections#150]
The [awx.awx.tower_credential module has deprecated the parameter `kind`](https://docs.ansible.com/ansible/latest/collections/awx/awx/tower_credential_module.html#parameter-kind) in favor or `credential_type`.

In [roles/credentials/tasks/main.yml:9](https://github.com/redhat-cop/tower_configuration/blob/c6b68596b18ff1579b2af028e56e927770c365a8/roles/credentials/tasks/main.yml#L9), this parameter is still provided to tower_credential, along the `credential_type` parameter.

An exported credential with awxkit 17.0.0 looks as follows:
```
tower_credentials:
- credential_type:
    kind: cloud
    name: '[DEMO] Demo Credential Type'
    type: credential_type
  description: ''
  inputs:
    demo_username: admin
  name: '[DEMO] Demo Credential'
  natural_key:
    credential_type:
      kind: cloud
      name: '[DEMO] Demo Credential Type'
      type: credential_type
    name: '[DEMO] Demo Credential'
    organization:
      name: Default
      type: organization
    type: credential
  organization:
    name: Default
    type: organization
```
Importing such credential will break since `kind` will have the value `cloud`, which is not authorized in [tower_credential.py from awx.awx](https://github.com/ansible/awx/blob/devel/awx_collection/plugins/modules/tower_credential.py#L281).

By simply removing [roles/credentials/tasks/main.yml:9](https://github.com/redhat-cop/tower_configuration/blob/c6b68596b18ff1579b2af028e56e927770c365a8/roles/credentials/tasks/main.yml#L9) and passing only `credential_type` (line 8 of the same file), the import for credentials of `cloud` or `external` types is correctly working.

Since `kind` is deprecared in awx.awx.tower_credential, perhaps it should be removed in the role.
