### ISSUE TITLE
Question on tower_roles

### ISSUE THREAD

**Issue by metabsd** [redhat-cop/automate_tower_genie_collections#177]
Hi,

Instead of 
```
---
tower_rbac:
  - inventory:  inventory1
    team: Unix
    role: use
  - inventory:  inventory2
    team: Unix
    role: use
  - inventory:  inventory3
    team: Unix
    role: use
 - inventory:  inventory1
    team: Unix
    role: update
  - inventory:  inventory2
    team: Unix
    role: update
  - inventory: inventory3
    team: Unix
    role: update
```

Can I use it like this :
```
---
tower_rbac:
  - use:
    team: Unix
    inventories:
      - inventory1
      - inventory2
      - inventory3
  - read:
    team: Unix
      inventories:
        - inventory1
        - inventory2
        - inventory3

```
So at the end I can add other resource in read like job_templates, workflows.
The module `awx.awx.tower_role` work like this I think.

Thx in advance!
