### ISSUE TITLE
No option to specify Privilege Escalation in Credentials role 

### ISSUE THREAD

**Issue by tonyreveal** [redhat-cop/automate_tower_genie_collections#182]
From reviewing the README and looking at tasks/main.yml, it appears there is no option available in the credentials role for specifying the privilege escalation method, privilege escalation username, or the privilege escalation password.  Can this be added?

**Comment by Tompage1994** [comment]
Credentials now work based on what is in each of the credential_types. So for the type of credential you're looking for (`Machine`) the `become_method` is just an input under the credential.

E.g.:

```
tower_credentials:
  - name: localuser
    credential_type: Machine
    inputs:
      username: localuser
      password: password
      become_method: sudo
```

I'll raise a PR to add this example to the readme for the credential role.

I'll also close this issue with the PR, but if you think this hasn't sufficiently answered your query let me know and we can reopen it and go into it further.
