### ISSUE TITLE
Using AWX Collection in playbook grabs older version of awx

### ISSUE THREAD

**Issue by suppaduppax** [redhat-cop/automate_tower_genie_collections#185]
Having the awx.awx collection as a parameter in the playbook uses an older version of that collection

```
- hosts: awx
  collections:
    - awx.awx
  tasks:
    - include_role:
        name: redhat_cop.tower_configuration.users
```

This was tested on a fresh Ubuntu Server vm when running the task:
```
    - include_role:
        name: redhat_cop.tower_configuration.users
```

which gives the error:
`Unsupported parameters for (tower_user) module: update_secrets`

When awx.awx collection is installed using: `ansible-galaxy collection install awx.awx`, the error disappears. 

This may be an Ansible issue but I am adding it as an issue just in case.
