### ISSUE TITLE
schedule role fails to remove when state: absent

### ISSUE THREAD

**Issue by tonyreveal** [redhat-cop/automate_tower_genie_collections#187]
Manually delete a schedule from Tower.  Then use the schedules role to remove the same schedule.  Or, run the playbook twice.  

The schedules role fails with ` returned 0 items, expected 1 `.  This is inconsistent behavior from the other roles in the collection.  Normally in this situation, the other roles (hosts, groups, job_templates, etc) will just determine the object to remove is not present, return "OK", and continue.  

```
---
- name: Test
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - awx.awx
    - redhat_cop.tower_configuration
  
  pre_tasks:
    - name: Include Tower specific vars
      include_vars: "tonylab_tower_config.yml"

  tasks:
    - name: Import vars for project, templates, and workflow
      include_vars: tonylab_workflow_cleanup.yml
    
    - name: Include vaulted vars
      include_vars: tonylab_tower_credentials_cleanup.yml
    
    - include_role:
        name: schedules
```

```
tower_schedules:
  - name: "ISAM Health Check Schedule"
    description: "Schedule for ISAM Health Checks"
    rrule: "DTSTART;TZID=America/New_York:20210527T000000 RRULE:FREQ=MINUTELY;INTERVAL=30"
    unified_job_template: "Isam Health Check"
    verbosity: 1
    state: absent
```

```
failed: [localhost] (item={'name': 'ISAM Health Check Schedule', 'description': 'Schedule for ISAM Health Checks', 'rrule': 'DTSTART;TZID=America/New_York:20210527T000000 RRULE:FREQ=MINUTELY;INTERVAL=30', 'unified_job_template': 'Isam Health Check', 'verbosity': 1, 'state': 'absent'}) => {"ansible_loop_var": "schedule_item", "changed": false, "msg": "Request to /api/v2/unified_job_templates/?name=Isam+Health+Check returned 0 items, expected 1", "query": {"name": "Isam Health Check"}, "response": {"json": {"count": 0, "next": null, "previous": null, "results": []}, "status_code": 200}, "schedule_item": {"description": "Schedule for ISAM Health Checks", "name": "ISAM Health Check Schedule", "rrule": "DTSTART;TZID=America/New_York:20210527T000000 RRULE:FREQ=MINUTELY;INTERVAL=30", "state": "absent", "unified_job_template": "Isam Health Check", "verbosity": 1}, "total_results": 0}
```
