### ISSUE TITLE
Schedules role does not modify existing schedule object

### ISSUE THREAD

**Issue by tonyreveal** [redhat-cop/automate_tower_genie_collections#199]
I used the schedules role to create a schedule in Tower:

```
    controller_schedules:
      - name: "ISAM Health Check Schedule {{ which_inventory }}"
        description: "Schedule for ISAM Health Checks"
        enabled: no
        extra_data:
          e2e_test_email_to: "abc@xyz.com"
          e2e_test_email_cc: "abc@xyz.com"
        rrule: "DTSTART;TZID=America/New_York:20210527T000000 RRULE:FREQ=MINUTELY;INTERVAL=30"
        unified_job_template: "Isam Health Check Workflow {{ which_inventory }}"
        verbosity: 1
        state: present
```

After the schedule was created I changed ` enabled: ` from ` no ` to ` yes ` and re-ran my playbook expecting that the schedule would be modified.  However the task returned OK without making any changes.  The schedule remained disabled.

```
    controller_schedules:
      - name: "ISAM Health Check Schedule {{ which_inventory }}"
        description: "Schedule for ISAM Health Checks"
        enabled: yes
        extra_data:
          e2e_test_email_to: "abc@xyz.com"
          e2e_test_email_cc: "abc@xyz.com"
        rrule: "DTSTART;TZID=America/New_York:20210527T000000 RRULE:FREQ=MINUTELY;INTERVAL=30"
        unified_job_template: "Isam Health Check Workflow {{ which_inventory }}"
        verbosity: 1
        state: present
```

```
TASK [redhat_cop.tower_configuration.schedules : Add Tower Schedule] ***************************************************
ok: [localhost] => (item={'name': 'ISAM Health Check Schedule ISAM', 'description': 'Schedule for ISAM Health Checks', 'enabled': False, 'extra_data': {'e2e_test_email_to': 'areveal@gmail.com', 'e2e_test_email_cc': 'tony.reveal@gmail.com'}, 'rrule': 'DTSTART;TZID=America/New_York:20210527T000000 RRULE:FREQ=MINUTELY;INTERVAL=30', 'unified_job_template': 'Isam Health Check Workflow ISAM', 'verbosity': 1, 'state': 'present'})
```

![image](https://user-images.githubusercontent.com/22101936/124660492-44fdfa00-de74-11eb-8678-0c2918e4fc93.png)

**Comment by tonyreveal** [comment]
This does seem to be an issue specific to the tower_configuration (controller_configuration) collection.  I am unable to reproduce the problem if just using the schedule module in the awx.awx collection.

```
- name: Update schedule
      awx.awx.schedule:
        name: "ISAM Health Check Schedule {{ which_inventory }}"
        description: "Schedule for ISAM Health Checks"
        enabled: yes
        extra_data:
          e2e_test_email_to: "abc@xyz.com"
          e2e_test_email_cc: "abc@xyz.com"
        rrule: "DTSTART;TZID=America/New_York:20210527T000000 RRULE:FREQ=MINUTELY;INTERVAL=30"
        unified_job_template: "Isam Health Check Workflow {{ which_inventory }}"
        verbosity: 1
        state: present
```

```
TASK [Update schedule] *************************************************************************************************
[WARNING]: You are using the awx version of this collection but connecting to Red Hat Ansible Tower
changed: [localhost]

PLAY RECAP *************************************************************************************************************
localhost                  : ok=1    changed=1
```
