### ISSUE TITLE
inventories role fails when no object and state is absent

### ISSUE THREAD

**Issue by tonyreveal** [redhat-cop/automate_tower_genie_collections#204]
If I create a playbook to use the inventories role to add a inventory it works. I can re-run the playbook and it does not modify the inventory if there are no changes to the inventory definition.

If I create a playbook to use the inventories role to remove the inventory ( state: absent ) it will work the first time. But if I run the playbook a second time it will fail as the object no longer exists. However it should not fail but rather determine that the required state already exists and continue on to the next task.

**Comment by tonyreveal** [comment]
```
failed: [localhost] (item={'name': 'ISAM', 'state': 'absent', 'organization': 'AT&T'}) => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "ansible_loop_var": "inventory", "changed": false, "inventory": {"name": "ISAM", "organization": "AT&T", "state": "absent"}, "msg": "Request to /api/v2/organizations/?name=AT%26T returned 0 items, expected 1", "query": {"name": "AT&T"}, "response": {"json": {"count": 0, "next": null, "previous": null, "results": []}, "status_code": 200}, "total_results": 0}
```

**Comment by sean-m-sullivan** [comment]
Did a test, issue at module level, Requires more logic for absent, hard to account for as well, Once inventory is removed, All hosts and groups from that inventory are removed from the Tower
```yaml
  tasks:
    - name: Remove organization
      awx.awx.organization:
        name: Something
        state: absent
      ignore_errors: true
    - name: Remove inventory
      awx.awx.inventory:
        name: Something
        organization: Something
        state: absent
      ignore_errors: true
    # fatal: [localhost]: FAILED! => {"changed": false, "msg": "Request to /api/v2/organizations/?name=Something returned 0 items, expected 1", "query": {"name": "Something"}, "response": {"json": {"count": 0, "next": null, "previous": null, "results": []}, "status_code": 200}, "total_results": 0}
    - name: Remove project
      awx.awx.project:
        name: Something
        organization: Something
        state: absent
      ignore_errors: true
    # fatal: [localhost]: FAILED! => {"changed": false, "msg": "Request to /api/v2/organizations/?name=Something returned 0 items, expected 1", "query": {"name": "Something"}, "response": {"json": {"count": 0, "next": null, "previous": null, "results": []}, "status_code": 200}, "total_results": 0}
    - name: Remove credential
      awx.awx.credential:
        name: Something
        organization: Something
        kind: github_token
        state: absent
      ignore_errors: true
    # fatal: [localhost]: FAILED! => {"changed": false, "msg": "Request to /api/v2/organizations/?name=Something returned 0 items, expected 1", "query": {"name": "Something"}, "response": {"json": {"count": 0, "next": null, "previous": null, "results": []}, "status_code": 200}, "total_results": 0}
```
