### ISSUE TITLE
execution_environments: The requested object could not be found at /api/v2/execution_environments/

### ISSUE THREAD

**Issue by dhikrahashim** [redhat-cop/automate_tower_genie_collections#220]
```
controller_execution_environments:
  - name: Tower env
    organization: OPS
    image: quay.io/ansible/awx-ee
    pull: always
  #- name: "network-info-ops"
  #   image: quay.io/argoproj/dataflow-python3-9
   #  pull: always

```
I am getting below error: 

failed: [localhost] (item={'name': 'Tower env', 'organization': 'OPS', 'image': 'quay.io/ansible/awx-ee', 'pull': 'always'}) => {"__execution_environments_item": {"image": "quay.io/ansible/awx-ee", "name": "Tower env", "organization": "OPS", "pull": "always"}, "ansible_loop_var": "__execution_environments_item", "changed": false, "msg": "The requested object could not be found at /api/v2/execution_environments/."}

What am i doing wrong here. I am running ansible tower 3.8.x

@sean-m-sullivan @Tompage1994 Execution environment works if the tower server running on containers ?
