### ISSUE TITLE
Not updating credentials when we create project

### ISSUE THREAD

**Issue by dhikrahashim** [redhat-cop/automate_tower_genie_collections#224]
When I create a project and mention the credential, everything updates except credentials.

```
controller_projects:
  - name: ansible-playbook-test
    scm_type: git
    scm_url: git@xxxxx:DC/xxxxxxx.git
    scm_branch: inventory-update
    description: Test inventory auto update and workflows
    organization: OPS
    credential: xxxxxx-OPS
    wait: true
    update: true
    scm_clean: 'yes'
    scm_delete_on_update: 'yes'
    scm_update_on_launch: 'yes'
    allow_override: 'yes'
```

@sean-m-sullivan  Could you please help me
