### ISSUE TITLE
use case of update role, example: project_update,inventory_source_update

### ISSUE THREAD

**Issue by dhikrahashim** [redhat-cop/automate_tower_genie_collections#228]
When we are going to remove any projects or inventory, if we enabled role like inventory_source_update and project_update and if it uses config from controller_projects and controller_inventory_sources

We are going to get  "couldn't find mentioned project"

"ansible_loop_var": "__project_update_update_item", "changed": false, "msg": "Unable to find project"

Because I mentioned the project state to absent and at the first role projects the play is removed the project and when project update role comes we are getting error

```
pre_tasks:
    - name: Include vars from configs directory
      include_vars:
        dir: ./configs
        ignore_files: [controller_config.yml.template]
        extensions: ["yml"]
  roles:
    - {role: projects, when: controller_projects is defined, tags: projects}
    - {role: inventories, when: controller_inventories is defined, tags: inventories}
    - {role: project_update, when: controller_projects is defined, tags: projects}
    - {role: inventory_sources, when: controller_inventory_sources is defined, tags: inventory_sources}
    - {role: inventory_source_update, when: controller_inventory_sources is defined, tags: inventory_sources}
    - {role: job_templates, when: controller_templates is defined, tags: job_templates}
```

@Tompage1994 @sean-m-sullivan @kedark3
