### ISSUE TITLE
Any wild card option in roles

### ISSUE THREAD

**Issue by dhikrahashim** [redhat-cop/automate_tower_genie_collections#232]
When we use roles (awx.awx.role) do we have any wild card option.

For example: 

1. We need to give admin access to specific pattern for projects,templates, inventory etc

Another question:

It will be good if we have more examples of this role use cases. Because when I am using "admin" role for an organization it is not working. I know for ORG we don't have admin option. 

May be if I want to give admin access to a team for specific org. What is the best way? Now I gave execute permission and people in the team are able to access only templates.

I am thinking about something like Jenkins casc pattern method

```
---
  controller_roles:
  ###### IHW Roles
    - team: "team_amh_ihw"
      job_templates:
        - inr-uat5-api-base-win
        - inr-uat5-cdn-base-win
      role: execute
      state: absent
    - team: "team_amh_inr"
      job_templates:
        - inr-uat5-api-base-win
        - inr-uat5-cdn-base-win
      role: execute

    - team: "team_ir_sre"
      job_templates:
        - IR-dev-ansible-playbook-ip-urls
      projects:
        - ansible-playbook-ip-urls
        - ansible-playbook-ip-codedeployment-datahub
      inventories:
        - IHW-ansible-playbook-ip-gcsurls
        - IHW-ansible-playbook-ip-codedeployment-datahub
      credentials:
        - git-IW
        - repo-IP
      role: admin
      state: present

###### OPS ORG roles

    - team: "team_ops_ir"
      organization: OPS
      role: execute
      state: present
```
      

@sean-m-sullivan  @Tompage1994 @kedark3

**Comment by Tompage1994** [comment]
Hi @dhikrahashim 

Unfortunately there is not a way to assign a role to a wildcard since the collection and its underlying modules simply make use of what's available on the API. 

[This section](https://docs.ansible.com/ansible-tower/3.8.4/html/userguide/security.html#rbac-ug) in the Ansible docs gives an overview of what roles can be set and how. 

In terms of being able to assign a role to multiple objects at the same time, that is also not currently possible due to limitations on the API which I imagine would not be easy to change. If you feel really strongly about making something like this possible I would recommend raising an issue on the [awx project](https://github.com/ansible/awx/) to make a change to the API to allow this and then modify the awx_collection (the upstream ansible.tower/ansible.controller collection) to allow providing multiple objects at the same time. 

I'm not saying its not a good idea - just that at the moment it wouldn't really be possible to implement on this collection. In theory you could write something yourself to take a variable as you've given above and convert to a format which can be taken by this collection but that seems like it may be more effort than its worth when it is reasonably straightforward to define a list of tuples (albeit a little bit longwinded), e.g.

```
controller_roles:
  - team: team_a
    job_template: jt_a
    role: execute
  - team: team_a
    job_template: jt_b
    role: execute
```
