### ISSUE TITLE
copy_from not working in notifcation_templates

### ISSUE THREAD

**Issue by dhikrahashim** [redhat-cop/automate_tower_genie_collections#233]
copy_from in notification templates is not working for me. Below is the code I am using

```
  - name: webhook-notification-MMP
    copy_from: webhook-notification-OPS
    organization: MMP
```

I already have one notification in the same config file with the same name webhook-notification-OPS

Below is the error

```
msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'notification_configuration'\n\nThe error appears to be in '/xxxxxxxxx/xxxxxx/roles/notification_templates/tasks/main.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: Add Controller notifications\n  ^ here\n"
```

**Comment by dhikrahashim** [comment]
It works!!! i have to use other parameters too.

```
notification_configuration:
      url: "{{ webhook_url }}"
      headers:
        "content-type": application/json
    state: present
 ```
