### ISSUE TITLE
controller_object_diff fils when the api list is empty

### ISSUE THREAD

**Issue by sean-m-sullivan** [redhat-cop/automate_tower_genie_collections#256]
controller_object_diff fils when the api list is empty
it should just put a warning up, and not fail the task. The reason being is if this is added into CI/CD to be a regular running task, that if the api compare list is empty, that means there is nothing to remove. 

Will look at this/process and decide which way forward is best, should the lookup fail, or should it warn, and have the user program around that. 
Was using this as the task

```
    - name: "Get the API list of all objects in the Organization"
      set_fact:
        projects_api_results: "{{ lookup('awx.awx.controller_api', 'projects', query_params={ 'organization': controller_organization_id.id } ,host=tower_server, oauth_token=tower_token, verify_ssl=false) | rejectattr('modified', 'greaterthan', check_time) | list }}"
        job_templates_api_results: "{{ lookup('awx.awx.controller_api', 'job_templates' ,host=tower_server, oauth_token=tower_token, verify_ssl=false) | rejectattr('modified', 'greaterthan', check_time) | list }}"
        workflow_job_templates_api_results: "{{ lookup('awx.awx.controller_api', 'workflow_job_templates' ,host=tower_server, oauth_token=tower_token, verify_ssl=false) | rejectattr('modified', 'greaterthan', check_time) | list }}"

    - name: "Find the difference of Objects between what is on the Controller versus curated list."
      set_stats:
        data:
          # controller_projects: "{{ lookup('redhat_cop.controller_configuration.controller_object_diff', api_list=projects_api_results, compare_list=controller_projects, with_present=false ,set_absent=true ) }}"
          controller_templates: "{{ lookup('redhat_cop.controller_configuration.controller_object_diff', api_list=job_templates_api_results, compare_list=controller_templates, with_present=false ,set_absent=true ) }}"
          controller_workflows: "{{ lookup('redhat_cop.controller_configuration.controller_object_diff', api_list=workflow_job_templates_api_results, compare_list=controller_workflows, with_present=false ,set_absent=true ) }}"
```
