### ISSUE TITLE
creating inventories show changed but nothing appears in the inventory on tower

### ISSUE THREAD

**Issue by weiyentan** [redhat-cop/automate_tower_genie_collections#277]
I have this data structure 

```
---
controller_inventories:
  - name: Kubernetes - User Cluster
    organization: Prometheus
    description: created by Ansible Playbook - Redhat Cop Tower Configuration
```

using the play book 

that is in the example given in the repository called configure_controller.yml

I get the result of this everytime:

```
TASK [inventories : Create inventory] ******************************************
changed: [localhost] => (item={'name': 'Kubernetes - User Cluster', 'organization': 'Prometheus', 'description': 'created by Ansible Playbook - Redhat Cop Tower Configuration'})
```

saying that it has changed something....but in actual fact it doesnt actually do anything. 

I suspect that I am not doing something right. Any help would be appreciated.
