### ISSUE TITLE
Update differential tests

### ISSUE THREAD

**Issue by sean-m-sullivan** [redhat-cop/automate_tower_genie_collections#280]
Update differential tests to be able to use a different search or no search and be able to do the following objects
group, host, workflow_job_template_node, user

Example code work that should work without the org being searched
```
  - name: groups
    query_params: ''
    with_present: false
    differential_test_items:
      - name: group1
        inventory: satlab-admin-inventory
      - name: group2
        inventory: satlab-admin-inventory
      - name: group3
        inventory: satlab-admin-inventory
    expected_test_result:
      - name: sat_lab_group
        inventory: satlab-admin-inventory
        state: absent
  - name: hosts
    with_present: false
    query_params: 'inventory: 7'
    differential_test_items:
      - name: localhost
        inventory: localhost
      - name: PSQL1
        inventory: satlab-admin-inventory
      - name: PSQL2
        inventory: satlab-admin-inventory
    expected_test_result:
      - name: PSQL3
        inventory: satlab-admin-inventory
        state: absent
```
