### ISSUE TITLE
Cannot add survey using `survey_spec` option

### ISSUE THREAD

**Issue by Tompage1994** [redhat-cop/automate_tower_genie_collections#291]
None of my templates were getting their surveys generated despite the template being able to source the json file with all the questions. By the looks of it, if I had used the ‘survey’ parameter instead of ‘survey_spec’ it would have worked first time, but I think this role should probably try follow the ansible.controller job template module as much as possible and that recommends ‘survey_spec’. Also the Readme says `survey_spec` is the correct option.

```
controller_templates:
  - name: "app_add"
    description: "Add Application"
    playbook: "update_app.yml"
    project: apps
    inventory: appsinv
    credentials:
      - Ansible SSH
    survey_enabled: true
    survey_spec: "{{ lookup('file', 'update_application.json') }}"
```
