### ISSUE TITLE
workflow error

### ISSUE THREAD

**Issue by djdanielsson** [redhat-cop/automate_tower_genie_collections#297]
I am trying to figure out if there is a bug in the role or if I have something wrong in the vars.

```
---
controller_workflows:
  - name: test_workflow
    description: testing issue
    extra_vars: ''
    survey_enabled: false
    allow_simultaneous: true
    ask_variables_on_launch: false
    ask_inventory_on_launch: false
    ask_scm_branch_on_launch: false
    ask_limit_on_launch: true
    webhook_service: ''
    organization: Default
    schedules: []
    simplified_workflow_nodes:
      - all_parents_must_converge: false
        identifier: node001
        unified_job_template: first_template
        credentials: []
        success_nodes: []
        failure_nodes:
          - node002
        always_nodes: []
      - all_parents_must_converge: false
        identifier: node002
        unified_job_template: second_template
        credentials: []
        success_nodes: []
        failure_nodes: []
        always_nodes: []
    notification_templates_started: []
    notification_templates_success: []
    notification_templates_error: []
    notification_templates_approvals: []
    survey_spec: {}
...
```

I get this error
```
FAILED! => {"msg": "The conditional check '__workflow_loop_item.state == \"present\"' failed. The error was: error while evaluating conditional (__workflow_loop_item.state == \"present\"): 'dict object' has no attribute 'state'\n\nThe error appears to be in '/home/user/.ansible/collections/ansible_collections/redhat_cop/controller_configuration/roles/workflow_job_templates/tasks/main.yml': line 62, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n# Create links between workflow node\n- name: loop over nodes in schema to add to workflow templates\n  ^ here\n"}
```

I did test removing this line https://github.com/redhat-cop/controller_configuration/blob/8028d7105a183da44915714754ab8f2ebe0d7995/roles/workflow_job_templates/tasks/main.yml#L69 and that works but I am not sure if that is the correct fix or if something else is wrong.
