### ISSUE TITLE
inventory_sources fails when Jinja variables are used in source_vars

### ISSUE THREAD

**Issue by zircon** [redhat-cop/automate_tower_genie_collections#321]
When using the following configuration:

```yaml
---
controller_inventory_sources:
  - name: ec2
    inventory: Demo Inventory
    organization: Default
    source: ec2
    source_vars:
      plugin: aws_ec2
      regions:
        - eu-central-1
      include_filters:
        - tag:Environment: test
      exclude_filters:
        - instance-state-name: stopped
      hostnames:
        - tag:Name
      compose:
        ansible_host: private_dns_name
      keyed_groups:
        - key: tags.Sponsor
          separator: ''
        - key: tags.Project
          separator: ''
          parent_group: '{{ tags.Sponsor }}'
    overwrite: true
    update_on_launch: true
```

The following failure occurs ('tags' is undefined):
```
TASK [redhat_cop.controller_configuration.inventory_sources : Add an inventory source] ********************************************************************
fatal: [localhost]: FAILED! => {"msg": "[{'name': 'ec2', 'inventory': 'Demo Inventory', 'organization': 'Default', 'source': 'ec2', 'source_vars': {'plugin': 'aws_ec2', 'regions': ['eu-central-1'], 'include_filters': [{'tag:Environment': 'test'}], 'exclude_filters': [{'instance-state-name': 'stopped'}], 'hostnames': ['tag:Name'], 'compose': {'ansible_host': 'private_dns_name'}, 'keyed_groups': [{'key': 'tags.Sponsor', 'separator': ''}, {'key': 'tags.Project', 'separator': '', 'parent_group': '{{ tags.Sponsor }}'}]}, 'overwrite': True, 'update_on_launch': True}]: 'tags' is undefined"}
```

This appears to be caused by the `parent_group: '{{ tags.Sponsor }}'` line. Unlike the `key` field of `keyed_groups`, `parent_group` can't be `tags.Sponsor` as it gets interpreted literally.
