### ISSUE TITLE
Compatibility with awx.awx.export / awxkit

### ISSUE THREAD

**Issue by luckylittle** [redhat-cop/automate_tower_genie_collections#332]
Please make this role compatible with `awx.awx.export` / `awxkit`. It does not work out of the box:

Steps to reproduce:

1. Run the export playbook:

```yaml
---
- hosts: localhost
  tasks:
  - name: Export all assets
    awx.awx.export:
      organizations: 'all'
    register: orgs_register

  - name: Store organizations as YAML in ./configs
    ansible.builtin.copy:
      content: "{{ orgs_register.assets | to_yaml }}"
      dest: "/home/redhat/Projects/awxkit/configs/organizations.yml"
```

2. It exports the following example file:

```yaml
organizations:
- default_environment: null
  description: This is one Business Unit in DEV
  max_hosts: 0
  name: NAB_BU_1_dev
  natural_key: {name: NAB_BU_1_dev, type: organization}
  related:
    execution_environments: []
    galaxy_credentials:
    - credential_type: {kind: galaxy, name: Ansible Galaxy/Automation Hub API Token,
        type: credential_type}
      name: Ansible Galaxy
      organization: null
      type: credential
    notification_templates: []
    notification_templates_approvals: []
    notification_templates_error: []
    notification_templates_started: []
    notification_templates_success: []
- default_environment: null
  description: Another business unit, but in PROD
  max_hosts: 0
  name: NAB_BU_2_prod
  natural_key: {name: NAB_BU_2_prod, type: organization}
  related:
    execution_environments: []
    galaxy_credentials:
    - credential_type: {kind: galaxy, name: Ansible Galaxy/Automation Hub API Token,
        type: credential_type}
      name: Ansible Galaxy
      organization: null
      type: credential
    notification_templates: []
    notification_templates_approvals: []
    notification_templates_error: []
    notification_templates_started: []
    notification_templates_success: []
```

3. Remove these two organizations from AAP

4. Run the playbook to configure AAP using the export from step 1:

```yaml
---
- name: Playbook to configure Ansible Controller
  hosts: localhost
  connection: local
  collections:
    - redhat_cop.controller_configuration
  pre_tasks:

    - name: Include vars from configs directory
      include_vars:
        dir: "{{ controller_configs_dir | default((lookup('env','CONTROLLER_CONFIGS_DIR') == '') | ternary('./configs', lookup('env','CONTROLLER_CONFIGS_DIR'))) }}"
        ignore_files: [controller_config.yml.template]
        extensions: ["yml"]
      tags:
        - always

  roles:
    - {role: organizations, when: controller_organizations is defined, tags: organizations}
```

*Expected result:* The role is compatible with `awxkit`. Two organizations will be re-added.

*Actual result:* Nothing happens, because the top level list is called the `organizations:` and the role expects `controller_organizations:`. When you add the prefix and re-run the playbook, it does import them successfully.

OS: Red Hat Enterprise Linux release v8.6 (Ootpa)
Ansible: core v2.12.2
awxkit: v21.3.0
redhat_cop.controller_configuration: v2.1.6

**Comment by luckylittle** [comment]
I came up with the below task, that transforms the data structure in the `./configs` folder:

```yaml
- name: Rename the top level item in ./configs directory
  ansible.builtin.replace:
    path: "{{ item }}"
    regexp: "^{{ item | basename | split('.') | first }}:$"
    replace: "controller_{{ item | basename | split('.') | first }}:"
  with_fileglob:
    - /home/lmaly/Projects/awxkit/configs/*
```
