### ISSUE TITLE
Update license role to use the new subscription module

### ISSUE THREAD

**Issue by sean-m-sullivan** [redhat-cop/automate_tower_genie_collections#355]
The current license role is a bit of a workaround for manifests, but we should use the new subscription module to make it easier to use. 

example playbook:
```
---
- name: Get subscription for controller
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - awx.awx
  tasks:
    - name: Get subscriptions with a filter
      awx.awx.subscriptions:
        username: redhat_username
        password: password
        filters:
          product_name: Red Hat Ansible Automation Platform
          support_level: Self-Support
        controller_host: https://controller.node
        controller_username: admin
        controller_password: secret123
        validate_certs: false
      register: subscription

    - name: Attach to a pool
      awx.awx.license:
        pool_id: "{{ subscription.subscriptions[0].pool_id }}"
        controller_host: https://controller.node
        controller_username: admin
        controller_password: secret123
        validate_certs: false
...
```
 If a manifest file is provided and specified, use it, otherwise use the pool entry, the product name in the example should work for most people subscriptions as default
