### ISSUE TITLE
Ability to store Job Templates as separate files

### ISSUE THREAD

**Issue by stephendorman** [redhat-cop/automate_tower_genie_collections#395]
# Job Templates as Separate Files
## Problem Statement
Something that bugged me about Controller CasC was the chonkiness of the `templates.yml` file. It was growing to be thousands of lines long which is not fun work with.

## My solution
Here was the solution I implemented: 

1. Broke the Job Templates out into separate files and added them to a folder `{{ controller_configs_dir }}/templates/`
2. Added a `_header.yml` that contains a single line for the `controller_templates:` var
3. Used `ansible.builtin.assemble` as a pre-task in `configure_controller.yml` to merge all the templates

### Examples
Little sample of what the filetree looks like
![templates](https://user-images.githubusercontent.com/12313968/197031355-28e7773e-e141-441e-a694-978a38acb365.png)

Contents of `_header.yml`
```yml
---
controller_templates:
```

Pre-task added in `configure_controller.yml`
```yml
  pre_tasks:
    - name: Merge templates
      ansible.builtin.assemble:
        src: "{{ controller_configs_dir }}/templates/"
        dest: "{{ controller_configs_dir }}/templates.yml"
```

## Conclusion
This may or may not be the right direction for this project, but I thought I'd bring it up since job template and workflow files can get unwieldy. I believe this solution - or something similar to it - would help make Controller CasC more manageable.
