### ISSUE TITLE
Add newly added promptable on launch vars to job_launch for AAP 2.3

### ISSUE THREAD

**Issue by ffirg** [redhat-cop/automate_tower_genie_collections#407]
In AAP 2.3 we have added everything that we could as a prompt on launch option when running job templates.
This has added more variables as per https://github.com/ansible/awx/pull/12875
Can we get these added to job_launch/tasks/main.yml ?
Will need to same exercise for workflows as well I suspect.

Thanks!

**Comment by ffirg** [comment]
I believe the JT vars list should be:

 execution_environment
 forks
 instance_groups
 job_slice_count

**Comment by sean-m-sullivan** [comment]
Slightly Behind, but needs testing, this is the WIP to get this done.
#406

**Comment by ffirg** [comment]
Nice! 

I added:

```
    execution_environment:    "{{ __job_launch_item.execution_environment | default(omit, true) }}"
    forks:                    "{{ __job_launch_item.forks | default(omit, true) }}"
    job_slice_count:          "{{ __job_launch_item.job_slice_count | default(omit, true) }}"
    instance_groups:          "{{ __job_launch_item.instance_groups | default(omit, true) }}"
```

forks and job_slice_count doesn't seem to be supported? The others worked.

Example config vars:
```
---
controller_launch_jobs:
  - name: Demo Job Template
    execution_environment: 1    # Minimal EE
    inventory: 1                # Demo Inventory
    instance_groups: [1,2]      # run on default, or then control plane

  - name: Demo Job Template
    execution_environment: 2    # Ansible Engine 2.9 EE
    inventory: 2                # SunCavanaugh Industries
    instance_groups: [4]        # newIG instance group
```
