### ISSUE TITLE
filetree_read and object_diff roles output is exposing credentials in clear text

### ISSUE THREAD

**Issue by rez-a-bug** [redhat-cop/automate_tower_genie_collections#446]
We need to add the secure logging variables to both filetree_read and object_diff roles to avoid having credentials in clear text in console output.

**Comment by adonisgarciac** [comment]
Thank you @rezfarsh. Totally agree that it is a good practice but I think it is only necessary to filetree_read role. 

Object_diff do calls to the api to get the credentials but passwords are getting with "$encrypted$"

**Comment by rez-a-bug** [comment]
@adonisgarciac object_diff is exposing the credentials when it is comparing the api list with controller_credentials var:

```yaml
- name: "Find the difference of Credentials between what is on the Controller versus CasC on SCM"
  ansible.builtin.set_fact:
    __credentials_difference: "{{ lookup('redhat_cop.controller_configuration.controller_object_diff',
                                          api_list=__controller_api_credentials, compare_list=controller_credentials,
                                          with_present=false, set_absent=true)
                               }}"

- name: "Set credential's list to be configured"
  ansible.builtin.set_fact:
    controller_credentials: "{{ __credentials_difference }}"
```
