### ISSUE TITLE
object_diff role support for `roles` , `settings` and ` teams` controllers ?

### ISSUE THREAD

**Issue by nodje** [redhat-cop/automate_tower_genie_collections#468]
I'm trying to use object_diff on roles & settings controller.

Evenb though the default.yml doesn't list them in `controller_configuration_object_diff_tasks` but at list they are referenced as variables in `# Automation Controller Object Lists`

A trial with the following playbook
    - role: redhat_cop.controller_configuration.object_diff
      vars:
        controller_configuration_object_diff_tasks:
          #- {name: settings, var: controller_settings, tags: settings }
          - {name: roles, var: controller_roles, tags: roles }

produces a weird error:
fatal: [localhost]: FAILED! => {
    "msg": "An unhandled exception occurred while running the lookup plugin 'redhat_cop.controller_configuration.controller_object_diff'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Key: 'name' missing from item in compare_list item: {'user': 'e75758', 'organization': 'BP2I CS21B - OS AIX MEO MOE', 'role': 'admin'}. Key: 'name' missing from item in compare_list item: {'user': 'e75758', 'organization': 'BP2I CS21B - OS AIX MEO MOE', 'role': 'admin'}"
}

I can't find any reference to a `name` Key in https://github.com/redhat-cop/controller_configuration/tree/devel/roles/roles
but I'm not sure I'm reading this correctly.

Trying on settings controllers produces a:
fatal: [localhost]: FAILED! => {
    "reason": "Could not find or access '/root/project/ansible/tower/automation-admin/settings.yml' on the Ansible Controller."
}

**Comment by adonisgarciac** [comment]
Hi, which version of collection are you using? It had a commit about object_diff plugin and roles and it is not in the public release 2.2.4: https://github.com/redhat-cop/controller_configuration/commit/500d8e82df69adf4be1218cfae158303a33e9b89.

Settings are not managed by object_diff: https://github.com/redhat-cop/controller_configuration/tree/devel/roles/object_diff/tasks

Settings is an unique object which will be defined with a json or a yaml dict. To sure the desired state you can define every setting in this json/yaml dict and your configuration as code will implement always these settings. Example defined settings:

```
controller_settings:
  - settings:
      ACTIVITY_STREAM_ENABLED: true
      ACTIVITY_STREAM_ENABLED_FOR_INVENTORY_SYNC: false
      AUTH_LDAP_GROUP_TYPE_PARAMS:
          member_attr: member
          name_attr: cn
      AUTOMATION_ANALYTICS_GATHER_INTERVAL: 14400
      AUTOMATION_ANALYTICS_LAST_ENTRIES: ''
      DEFAULT_EXECUTION_ENVIRONMENT: null
      INSIGHTS_TRACKING_STATE: true
      INSTALL_UUID: XXXXXXXXXXXXXXX
      LICENSE:
          instance_count: 100
          license_date: XXXXXXXXX
          license_type: enterprise
          pool_id: XXXXXXXXXXXXX
          product_name: Red Hat Ansible Automation Platform
          satellite: null
          sku: XXXXXXXXXXX
          subscription_name: XXXXXXXXXXXXXXx
          support_level: Standard
          valid_key: true
      MANAGE_ORGANIZATION_AUTH: true
      ORG_ADMINS_CAN_SEE_ALL_USERS: true
      PENDO_TRACKING_STATE: detailed
      PROXY_IP_ALLOWED_LIST: []
      REDHAT_PASSWORD: ''
      REDHAT_USERNAME: ''
      REMOTE_HOST_HEADERS:
      - REMOTE_ADDR
      - REMOTE_HOST
      SUBSCRIPTIONS_USERNAME: user
      TOWER_URL_BASE: https://192.168.1.1
```
