### ISSUE TITLE
filetree_create.yml is not capturing notification settings for projects, job_templates, workflow_job_templates

### ISSUE THREAD

**Issue by the-it-jaeger** [redhat-cop/automate_tower_genie_collections#526]
# Summary

`filetree_create.yml` does not capture job_tempalte or project notification settings.

# Issue Type

- Bug Report

# Ansible, Collection, Controller details

```console (paste below)
ansible --version
ansible [core 2.14.0]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/vhaispjaegea0/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/vhaispjaegea0/.ansible/collections:/usr/share/ansible/collections
  executable location = /bin/ansible
  python version = 3.9.13 (main, Nov  9 2022, 13:16:24) [GCC 8.5.0 20210514 (Red Hat 8.5.0-15)] (/usr/bin/python3.9)
  jinja version = 3.1.2
  libyaml = True

ansible-galaxy collection list
Collection                          Version
----------------------------------- -------
ansible.controller                  4.3.0
awx.awx                             21.10.2
redhat_cop.controller_configuration 2.2.4

Controller version
<  Ansible Automation Platform Controller 4.3.0  >
```

- ansible installation method: OS package

# OS / ENVIRONMENT

Host where filetree_create.yml is running: Red Hat Enterprise Linux release 8.7 (Ootpa)

# Desired Behavior

Would like to see notification settings captured for projects, job_templates, and workflow_job_templates

# Actual Behavior

For example:

![image](https://user-images.githubusercontent.com/61639149/223460385-b965cda2-e8d5-475a-8147-1d1008b6585b.png)

```
---
controller_projects:
  - name: "EPMO/helm-valip-iris-deploy"
    description: ""
    organization: "helm-valip-iris"
    scm_type: "git"
    scm_url: "git@github.ec.va.gov:EPMO/helm-valip-iris-deploy.git"
    scm_credential: "VAEC GitHub SSH Key"
    scm_branch: ""
    scm_clean: "True"
    scm_delete_on_update: "True"
    scm_update_on_launch: "True"
    scm_update_cache_timeout: "0"
    allow_override: "True"
    timeout: 0
...
```
# STEPS TO REPRODUCE

Run filetree_create.yaml playbook and checkr captured configuration YAML for projects, job_templates, and workflow_job_templates which lack notification settings information

```yaml (playbook/task)
ansible-playbook filetree_create.yml -e @./vault_controller_config.yml --ask-vault-pass
```
