### ISSUE TITLE
Object diff for roles removing most roles

### ISSUE THREAD

**Issue by bogdanmuresan** [redhat-cop/automate_tower_genie_collections#552]
# Summary

There are several things not working with object diff for roles. In our case, it marks most of the roles for removal.
From what I can tell, it will only work for target_teams, job_templates and workflows, as there are the only ones expanded here:
https://github.com/redhat-cop/controller_configuration/blob/devel/plugins/lookup/controller_object_diff.py#L221-L243

This means it will not work for projects, inventories, credentials.

Furthermore, all keys of the compared objects must match: https://github.com/redhat-cop/controller_configuration/blob/devel/plugins/lookup/controller_object_diff.py#L279
So even for job_templates, or target_teams, this will not work if we add "organization" or "lookup_organization", as these are not returned by the api in the role object - and the keys will not match.

# Issue Type

- Bug Report

# Ansible, Collection, Controller details

redhat_cop.controller_configuration: 2.2.5

# STEPS TO REPRODUCE
Here are a couple of test scenarios, where the entries will be marked for removal (state: absent):

1. Role will be set to state: absent, because the target_team is not handled - workaround is to use target_teams list
```yaml
---
controller_roles:
  - user: myuser
    target_team: myteam
    role: member
```

2. Inventories not expanded
```yaml
---
controller_roles:
  - team: myteam
    inventories:
      - inv1
      - inv2
    role: use
```
3. Projects not expanded
```yaml
---
controller_roles:
  - team: myteam
    projects:
      - project1
      - project2
    role: use
```
4. Credentials not expanded
```yaml
---
controller_roles:
  - team: myteam
    credentials:
      - secret1
      - secret2
    role: use
```

4. lookup_organization is an extra key not handled by object diff
```yaml
---
controller_roles:
  - team: myteam
    lookup_organization: Acme
    job_templates:
      - jd1
      - jd2
    role: execute
```

4. organization is an extra key not handled by object diff
```yaml
---
controller_roles:
  - user: myuser
    organization: Acme
    target_teams:
      - teams1
    role: member
```

**Comment by ivarmu** [comment]
Hi @bogdanmuresan,

I'm not proud of that piece of code, but it's the only way I found to match all the possibilities for the roles object.

I have in mind that there was an issue or something like that in awx project to get the roles in a more standard way, so diffing them should be an easier task, but I'm not sure about that point.

By now, I've added support for the singulars at the PR #562. You can see that adding all the fields can generate a large piece of code, so I'm trying to simplify that code by some way and updating the PR.

**Comment by ivarmu** [comment]
@bogdanmuresan, in the `lookup_organization is an extra key not handled by object diff`, the `lookup_organization` is not an item provided by the API for the role object, so it can't be used to be compared. The same happens with the `organization is an extra key not handled by object diff`, the organization is not a field returned in the role object by the API. So... I'm not sure what to do with these fields... are they really causing problems?

**Comment by bogdanmuresan** [comment]
Hi @ivarmu . Thank you for looking into this.
We are using lookup_organization as described here:
https://github.com/redhat-cop/controller_configuration/blob/fddeeffcefa0089e7c9aec5ebfb73cd761dc97df/roles/roles/README.md?plain=1#L76

As for the organization, my assumption is this needs to be extracted from the "related" user or team, same as for the username and team name: https://github.com/redhat-cop/controller_configuration/blob/devel/roles/object_diff/tasks/roles.yml#L46

If lookup_organization is present, the organization field would need to be moved up one level from the "related" object (job_template, inventory, etc), in order to support multiple organizations. But as there are already so many api calls made, this would case additional api calls and make it even slower than it is now (https://github.com/redhat-cop/controller_configuration/discussions/538), so I am not sure what the best approach would be.

**Comment by mmaaz1** [comment]
I am currently facing similar issues with object_diff and roles on controller_configuration: 2.5.2. 

For example, just going from "credential" to "credentials" will cause object_diff to not work. I think this issue should be re-opened.

```
controller_roles:
- role: admin
  team: My Team
  credentials:  
    -  My Credential
```
