### ISSUE TITLE
Mandatory rrule in shedules

### ISSUE THREAD

**Issue by jpcarmona** [redhat-cop/automate_tower_genie_collections#584]
# Summary

Hello!

Could it be that the "rrule" parameter in the "schedules" role does not have to be mandatory?
https://github.com/redhat-cop/controller_configuration/blob/devel/roles/schedules/tasks/main.yml#L7

In awx.awx and ansible.controller collections do not appear as required:
https://docs.ansible.com/ansible/latest/collections/awx/awx/schedule_module.html#parameter-rrule
https://console.redhat.com/ansible/automation-hub/repo/published/ansible/controller/content/module/schedule/?version=4.3.0

# Issue Type

- Bug Report

# Ansible, Collection, Controller details

```console
ansible.controller              4.3.0  
ansible.utils                   2.5.0  
awx.awx                         21.14.0 
community.general               4.4.0  
infra.controller_configuration  2.3.1_devel 
```

# ERROR

```console (error)

TASK [infra.controller_configuration.schedules : Add Controller Schedule] ************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "Mandatory variable 'rrule'  not defined."}

```

# STEPS TO REPRODUCE

```yaml (playbook/task)

- name: "Delete schedule"
  ansible.builtin.include_role:
    name: "schedules"
  vars:
    controller_schedules:
      - name: "schedule_to_delete"
        state: absent

```

Great job on this collection!
Best regards
