### ISSUE TITLE
The Roles role uses incorrect values when it starts after the Object_diff role

### ISSUE THREAD

**Issue by dmnagornyi** [redhat-cop/automate_tower_genie_collections#594]
# Summary

When you run the Roles role after the Object_diff role, all roles that should be removed fail with an error:

```
"value of role must be one of: admin, read, member, execute, adhoc, update, use, approval, auditor, project_admin, inventory_admin, credential_admin, workflow_admin, notification_admin, job_template_admin, execution_environment_admin, got: notification admin"
```

Same for "job template admin", "execution environment admin" and other roles with "_" sign in the name.

For some reason, all "_" characters are replaced with a space character for role values. There is no problem with the "member" role, since it only consists of one word.

# Issue Type

- Bug Report

# Ansible, Collection, Controller details

```console (paste below)
ansible --version
ansible [core 2.14.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.13 (main, Nov  9 2022, 13:16:24) [GCC 8.5.0 20210514 (Red Hat 8.5.0-15)] (/usr/bin/python3.9)
  jinja version = 3.1.2
  libyaml = True

ansible-galaxy collection list
# /root/.ansible/collections/ansible_collections
Collection                     Version
------------------------------ -------
ansible.controller             4.3.0
infra.controller_configuration 2.3.1

Controller version

```

- ansible installation method: OS package from AAP installer

# OS / ENVIRONMENT

Red Hat Enterprise Linux release 8.7 (Ootpa)

# Desired Behavior

Those roles that are missing in the code and were defined by the Object_diff role are removed by the Roles role after the list of missing objects is generated.

# Actual Behavior

Playbook crashed due to invalid value.

```console (error)
failed: [127.0.0.1] (item={'failed': 0, 'started': 1, 'finished': 0, 'ansible_job_id': '875427140397.7339', 'results_file': '/tmp/.ansible_async/875427140397.7339', 'changed': False, '__controller_role_item': {'role': 'inventory admin', 'team': 'Automation-Admins', 'organizations': ['Automation'], 'state': 'absent'}, 'ansible_loop_var': '__controller_role_item'}) => {"__controller_role_job_async_results_item": {"__controller_role_item": {"organizations": ["Automation"], "role": "inventory admin", "state": "absent", "team": "Automation-Admins"}, "ansible_job_id": "875427140397.7339", "ansible_loop_var": "__controller_role_item", "changed": false, "failed": 0, "finished": 0, "results_file": "/tmp/.ansible_async/875427140397.7339", "started": 1}, "ansible_job_id": "875427140397.7339", "ansible_loop_var": "__controller_role_job_async_results_item", "attempts": 1, "changed": false, "finished": 1, "msg": "value of role must be one of: admin, read, member, execute, adhoc, update, use, approval, auditor, project_admin, inventory_admin, credential_admin, workflow_admin, notification_admin, job_template_admin, execution_environment_admin, got: inventory admin", "results_file": "/tmp/.ansible_async/875427140397.7339", "started": 1, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
```

# STEPS TO REPRODUCE

Create a team and assign several roles that are not defined in the code repository. Then run the playbook to remove the undeclared objects.

```yaml (playbook/task)
    - name: Include roles role
      ansible.builtin.include_role:
        name: infra.controller_configuration.roles
        apply:
          tags: roles
      when: controller_roles | length is not match('0')
      tags: roles

    - name: Include object_diff role
      ansible.builtin.include_role:
        name: infra.controller_configuration.object_diff
      tags: roles

    - name: Include roles role
      ansible.builtin.include_role:
        name: infra.controller_configuration.roles
        apply:
          tags: roles
      when: controller_roles | length is not match('0')
      tags: roles
```

```yaml (config/list/array/variables)

```

[minimum complete verifiable example]: http://stackoverflow.com/help/mcve
