### ISSUE TITLE
Variable non interpolated in controller_settings when used as a dict's key

### ISSUE THREAD

**Issue by nodje** [redhat-cop/automate_tower_genie_collections#607]
Using 2.3.1

When the var is used precisely as a dict **key** for in a **dict value** it doesn't get interpolated and the value is put "as is" in the settings.

For instance:
```
---
controller_settings:
  - settings:
      SOCIAL_AUTH_SAML_ORGANIZATION_MAP:
        "{{ oracle_org}}":
          "remove_admins": false
          "admins":
            - "admin1@org.com"

```
{{ oracle_org }} is put as is in the SOCIAL_AUTH_SAML_ORGANIZATION_MAP setting.

Not sure if this is supported to be supported.
Maybe it also doesn't work as an "upper level dict key"

**Comment by sean-m-sullivan** [comment]
what are you wanting it to say, not sure why its not interpreting the var.

**Comment by nodje** [comment]
What I'm trying to say is that the string "{{ oracle_org }}" is not replaced by it's value as declared in the playbook, where it's correctly replaced for all other instances.

So far ONLY in this situation, when it's inserted as a setting dict's key it isn't replaced.

**Comment by adonisgarciac** [comment]
Have you gotten the controller_settings with filetree_create or did you write it manually?

Anyway, can you try something like:
```
---
controller_settings:
  - settings:
      SOCIAL_AUTH_SAML_ORGANIZATION_MAP:
         '{{ '{{' }} oracle_org {{ '}}' }}':
          "remove_admins": false
          "admins":
            - "admin1@org.com"
```

**Comment by nodje** [comment]
FYI, it's a mix, I received the file from filetree_create initially then heavily modified and split the settings into multiple files.

Filetree_read chokes on this `'{{ '{{' }} oracle_org {{ '}}' }}':` with syntax issue.

**Comment by DLV1810** [comment]
This is what we do for this - gives us the ability to manage vars as keys (with strings as well if needed)

We set the vars in elsewhere and just consume it it in the config - it should work inline as well as we're only doing a set fact.


```yaml
    __org_mappings:
      ldap_teams: "{{ {
            __org_map_and_team_map.name + ' Admins':
            {
              'organization': __org_map_and_team_map.name,
              'remove': __org_map_and_team_map.remove_users,
              'users': __org_map_and_team_map.admin_groups,
            },
            __org_map_and_team_map.name + ' Users':
            {
              'organization': __org_map_and_team_map.name,
              'remove': __org_map_and_team_map.remove_users,
              'users': __org_map_and_team_map.user_groups,
            },
          } }}"
```

**Comment by nodje** [comment]
Thanks for this tip David, I'll give it a try

**Comment by sean-m-sullivan** [comment]
I would also try unsafe to have it not interpret things, If neither of these work, please reopen the issue
```
    injectors:
      env:
        AH_PASSWORD: !unsafe "{{ password }}"
        AH_USERNAME: !unsafe "{{ username }}"
      extra_vars:
        ah_password: !unsafe "{{ password }}"
        ah_username: !unsafe "{{ username }}"
```
