### ISSUE TITLE
Tower Settings role needs rewritten to use faster process

### ISSUE THREAD

**Issue by sean-m-sullivan** [redhat-cop/automate_tower_genie_collections#62]
Tower Settings should add the settings option and use it to send all the settings in one task without a loop. This will speed up the process of the role. 
```
- name: Set all the LDAP Auth Bind Params
  tower_settings:
    settings:
      AUTH_LDAP_BIND_PASSWORD: "password"
      AUTH_LDAP_USER_ATTR_MAP:
        email: "mail"
        first_name: "givenName"
        last_name: "surname"
```
