### ISSUE TITLE
Inventory Source - wrong default for source_project when source not scm

### ISSUE THREAD

**Issue by bogdanmuresan** [redhat-cop/automate_tower_genie_collections#627]
# Summary

When defining an inventory source that is not of source/type scm, and has no source_project, there is an error similar to "Request to /api/v2/projects/?organization=2 returned 45 items, expected 1" - From what I noticed, even though there is no source_project key, a source project key is sent to the inventory_source module with an empty string (""), and it causes it to search for projects containing empty string (source_project is no longer None/null/undefined).

https://github.com/ansible/awx/blob/devel/awx_collection/plugins/modules/inventory_source.py#L266

My assumption is the problem is here: 
https://github.com/redhat-cop/controller_configuration/blob/devel/roles/inventory_sources/tasks/main.yml#L25

Error is in 2.4.0, and it worked with 2.3.1
Enforce defaults is set to false

# Issue Type

- Bug Report

# Ansible, Collection, Controller details

```console (paste below)
AAP latest version
infra.controller_configuration  version 2.4.0 (latest) running with awx.awx 22.3.0 (because with ansible.controller 4.3.0 there are other issues)

```

- ansible installation method: one of source, pip, OS package, EE

# OS / ENVIRONMENT

# Desired Behavior

When inventory_source is omitted in an controller_inventory_sources, it should also be ommited when sent to the inventory_source module, and not be sent as empty string.

Sample inventory source:
```yaml 
---
controller_inventory_sources:
  - name: vcenter01
    organization: Acme
    credential: vcenter
    execution_environment: VMware execution environment
    source: vmware
    inventory: vmware
    verbosity: 1
    overwrite: true
    overwrite_vars: true
    update_cache_timeout: 0
    update_on_launch: false
```

[minimum complete verifiable example]: http://stackoverflow.com/help/mcve
