### ISSUE TITLE
"__contents_filetree_controller_settings": "VARIABLE IS NOT DEFINED!" when it actually is! (Kinda)

### ISSUE THREAD

**Issue by DLV1810** [redhat-cop/automate_tower_genie_collections#646]
# Summary

When defining controller_settings (or probably any other setting for that matter) if you have a variable which is undefined or spelling mistake, as was in my case the whole var is picked up as not defined, so it skips over "silently" applying any future config for that var.

# Issue Type

- Bug Report

# Ansible, Collection, Controller details

# Desired Behavior

Have some intelligence in there which can detect and exit out.

# Actual Behavior

```
- debug:
    var=__contents_filetree_controller_settings

TASK [redhat_cop.controller_configuration.filetree_read : debug] ***********************************************************************************************************************************
ok: [vnl00008349.privatecloud.dev.au.internal.cba -> localhost] => {
    "__contents_filetree_controller_settings": "VARIABLE IS NOT DEFINED!"
}
```
But with a couple of -vv enabled, we see there is data in there, but the dict object name is "VARIABLE IS NOT DEFINED!:"

```bash
TASK [redhat_cop.controller_configuration.filetree_read : debug] ***********************************************************************************************************************************
task path: /home/xxxxx/aap/ansible-automation-platform/collections/ansible_collections/redhat_cop/controller_configuration/roles/filetree_read/tasks/settings.yml:17
ok: [vnl00008349.privatecloud.dev.au.internal.cba -> localhost] => {
    "__contents_filetree_controller_settings": "VARIABLE IS NOT DEFINED!: {'results': [{'ansible_included_var_files': ['/home/xxxx/aap/ansible-automation-platform/inventory/ansibleplatform/blah/env/sandbox/controller_settings.d/settings_base.yml'], 'ansible_facts': {'controller_settings': [{'name': 'TOWER_URL_BASE', 'value': 'https://xxxxxxx/'},  <snip...>
'aap_enviaronment_display_name' is undefined <-- this was the spelling mistake
```

**Comment by DLV1810** [comment]
So i've opened this for some discussion on the best way to detect and fix, I've been looking at seeing if we can see if the length of the object

```
- debug:
    var=__contents_filetree_controller_settings['VARIABLE IS NOT DEFINED!']
```

But the issue always is that ansible thinks the var isn't defined so its hard to do logic against it - you can't do length of an object ansible think's is undefined

This actually seems to work - but def needs some feedback if its the right way

```
- name: "Read Settings definitions"
  ansible.builtin.include_vars:
    file: "{{ __read_settings_definitions_item.path }}"
  loop: "{{ __list_files_controller_settings.files }}"
  loop_control:
    loop_var: __read_settings_definitions_item
  register: __contents_filetree_controller_settings

# Hack to see if a var is undefined
- name: Assert that we're not hitting an issue
  ansible.builtin.assert:
    that:
      - "'is undefined' not in __contents_filetree_controller_settings"
```

**Comment by adonisgarciac** [comment]
Can you share the content of /home/xxxx/aap/ansible-automation-platform/inventory/ansibleplatform/blah/env/sandbox/controller_settings.d/settings_base.yml?

**Comment by DLV1810** [comment]
Here's a snippet of it - the var under CUSTOM_LOGIN_INFO had a typo in it, so the var was undefined

```
controller_settings:
  - name: TOWER_URL_BASE
    value: https://URL/
  - name: ORG_ADMINS_CAN_SEE_ALL_USERS
    value: 0  # False - If set to False it changes every run
  - name: CUSTOM_LOGIN_INFO
    value: Ansible Tower <b>{{ aap_environment_display_name }}</b><br/><br/>Authorised users only
```

**Comment by sean-m-sullivan** [comment]
Will have to look into this, and see what the API/Module is reading/accetping. Generally its not the roles, they are particularly dumb in cases like this, just wrappers on the modules that do the actual work. 

Have you tried:
```
controller_settings:
  settings:
    TOWER_URL_BASE: https://URL/
    ORG_ADMINS_CAN_SEE_ALL_USERS: 0
    CUSTOM_LOGIN_INFO: Ansible Tower <b>{{ aap_environment_display_name }}</b><br/><br/>Authorised users only
```
It runs faster and cleaner, but may still error out.

**Comment by DLV1810** [comment]
Thanks - I think we ended up going with the other method due to having things like this and it saying you can't have a dict - it has to be key/value only - I guess we could create 2 files, one with the key/value and the other with the dict's - or is there a nice trick you're about to advise me of 😄 

```yaml
  - name: OAUTH2_PROVIDER
    value:
      ACCESS_TOKEN_EXPIRE_SECONDS: aa
      AUTHORIZATION_CODE_EXPIRE_SECONDS: bb
      REFRESH_TOKEN_EXPIRE_SECONDS: cc
```
