### ISSUE TITLE
Improvement: De-duplicate task in roles role

### ISSUE THREAD

**Issue by Tompage1994** [redhat-cop/automate_tower_genie_collections#661]
Maybe you can reduce code/task duplication with the following idea:
```yaml
---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    - data:
        - name: row1
          roles:
            - role1
            - role2
        - name: row2
          role: roleA
  tasks:
    - debug:
        msg:
          - "{{ item.1 if item.1 is defined else item.role }}"
      loop: "{{ (data | selectattr('role', 'defined')) + (data | subelements(['roles'], skip_missing=true)) }}"
...
```

_Originally posted by @ivarmu in https://github.com/redhat-cop/controller_configuration/pull/658#pullrequestreview-1556989197_
