### ISSUE TITLE
Assigning Default Environment to Organization

### ISSUE THREAD

**Issue by willtome** [redhat-cop/automate_tower_genie_collections#671]
# Summary
I'm not sure if this is intended behavior however when assigning the default environment to an organization, it requires a dictionary instead of a string. Either role or documentation needs to be updated.

# Issue Type

- Bug Report

# Ansible, Collection, Controller details

```console (paste below)
ansible --version

Controller versionansible [core 2.15.0]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/lab-user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/lab-user/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.7 (default, Sep 13 2021, 08:18:39) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)] (/usr/bin/python3.9)
  jinja version = 3.1.2
  libyaml = True

ansible-galaxy collection list

# /home/lab-user/test/collections/ansible_collections
Collection                     Version
------------------------------ -------
amazon.aws                     2.2.0  
ansible.posix                  1.3.0  
ansible.utils                  2.7.0  
awx.awx                        22.6.0 
community.general              4.6.1  
infra.controller_configuration 2.5.0  
kubernetes.core                2.3.1  

Controller version: 4.4.1

```

- ansible installation method: OS package

# OS / ENVIRONMENT

RHEL 8.6

# Desired Behavior

When an organization is defined as documented, the default_environment is assigned to the org.
```
  controller_organizations:
      - name: Default
        default_environment: 'product-demos'
        galaxy_credentials:
          - Ansible Galaxy
          - Automation Hub
```

However, looking at [this line](https://github.com/redhat-cop/controller_configuration/blob/8b97ad07815a921bc8a33871e05b609c97966107/roles/organizations/tasks/main.yml#L9) it appears that the default_environment parameter is expecting a dictionary. When the variables are defined like this it works as expected.

```
    controller_organizations:
      - name: Default
        default_environment: 
          name: 'product-demos'
        galaxy_credentials:
          - Ansible Galaxy
          - Automation Hub
```
