### ISSUE TITLE
Failing to interpolate variables in Controller definitions when using object_diff role

### ISSUE THREAD

**Issue by nodje** [redhat-cop/automate_tower_genie_collections#695]
Using 4.4.2

This is not the first time I bump into these errors and they are still painfully hard to debug because it all fails silently:
- definition is read with the variables and does not show any issue (-v shows the controller definition with the variable, not their value)
- then the "Create Ansible Controller xxxx" task shows skipping and you can't know why.

The odd thing is that it CAN work with variables, but afa i've been able to identify, they at least don't work when they are in first position in a controller definition file.
e.g.
```
---
controller_teams:
  - name: "BP2I AL10B - Automation Clouds"
    description: ""
    organization: "BP2I AL10B - Automation Clouds"

  - name: "{{ aix_org }}"
    description: ""
    organization: "{{ aix_org }}"

  - name: "{{ windows_org }}"
    description: ""
    organization: "{{ windows_org }}"
....
```
does work.

But this does not:

```
controller_teams:
  - name: "{{ windows_org }} Global inventories team"
    description: ""
    organization: "{{ orgs }}"

  - name: "{{ aix_org }} Global inventories DC1 team"
    description: ""
    organization: "{{ orgs }}"

  - name: "{{ aix_org }} Global inventories DC2 team"
    description: ""
    organization: "{{ orgs }}"
```
and fails silently

---------------------
last definition of a controller files having variable seems to make it fails as well
