### ISSUE TITLE
Inventory Sources cannot be deleted via object_diff since 2.6.0

### ISSUE THREAD

**Issue by dbk-rabel** [redhat-cop/automate_tower_genie_collections#738]
# Summary

Since updating to 2.6.0, we cannot delete inventory sources anmore with the output from object_diff

object_diff Role does not output a 'source' parameter for inventory_source objects. But as of https://github.com/redhat-cop/controller_configuration/commit/a79f987765ae7d6ba5763c6d45c56ea7d325ec3f , the inventory_sources role fails without a 'source' parameter.

I think the change in https://github.com/redhat-cop/controller_configuration/commit/a79f987765ae7d6ba5763c6d45c56ea7d325ec3f is generally not stable, since it is not possible to omit the 'source' parameter anymore. The default is never evaluated, because it fails before.

# Issue Type

- Bug Report

# Ansible, Collection, Controller details

infra.controller_configuration 2.6.0

# STEPS TO REPRODUCE

Here is a reduced way to reproduce this. I did not use object_diff, but just copy-pasted what object_diff gave me. Also you have to first create the other referenced objects to test this.

```yaml (playbook/task)
---
- name: Issue replication
  hosts: localhost
  gather_facts: false
  collections:
    - ansible.controller

  tasks:
  - name: Add an inventory source
    vars:
      controller_inventory_sources:
        - name: 'inv_src_rabel-test'
          inventory: 'inv_rabel-test'
          organization: 'org_rabel-test'
          source: 'scm'
          source_project: 'prj_inv_rabel-test'
          source_path: ''
          credential: 'cred_rabel-test_git'
      controller_configuration_inventory_sources_enforce_defaults: true
    ansible.builtin.include_role:
      name: infra.controller_configuration.inventory_sources


  - name: Remove an inventory source
    vars:
      controller_inventory_sources:
        - name: 'inv_src_rabel-test'
          inventory: 'inv_rabel-test'
          organization: 'org_rabel-test'
          state: 'absent'
      controller_configuration_inventory_sources_enforce_defaults: true
    ansible.builtin.include_role:
      name: infra.controller_configuration.inventory_sources

```
```console (error)
$ ansible-playbook aap_reproduce2.yml
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [Issue replication] ********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************

TASK [Add an inventory source] **************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************

TASK [infra.controller_configuration.inventory_sources : Validating arguments against arg spec 'main' - An Ansible Role to create inventory sources on Ansible Controller.] *****************************************************************************************************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [infra.controller_configuration.inventory_sources : Managing Inventory Sources] ********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
ok: [localhost] => (item=Create/Update an Inventory Source inv_src_rabel-test)

TASK [infra.controller_configuration.inventory_sources : Flag for errors (check mode only)] *************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
skipping: [localhost]

TASK [infra.controller_configuration.inventory_sources : Managing Inventory Sources | Wait for finish the Inventory Sources management] *****************************************************************************************************************************************************************************************************************************************************************************************************************************************************
FAILED - RETRYING: [localhost]: Managing Inventory Sources | Wait for finish the Inventory Sources management (30 retries left).
FAILED - RETRYING: [localhost]: Managing Inventory Sources | Wait for finish the Inventory Sources management (29 retries left).
ok: [localhost] => (item=Create/Update Inventory Source {'failed': 0, 'started': 1, 'finished': 0, 'ansible_job_id': '217206866691.2149146', 'results_file': '/home/rabel/.ansible_async/217206866691.2149146', 'changed': False, '__controller_source_item': {'name': 'inv_src_rabel-test', 'inventory': 'inv_rabel-test', 'organization': 'org_rabel-test', 'source': 'scm', 'source_project': 'prj_inv_rabel-test', 'source_path': '', 'credential': 'cred_rabel-test_git'}, 'ansible_loop_var': '__controller_source_item'} | Wait for finish the Inventory Source creation)

TASK [Remove an inventory source] ***********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************

TASK [infra.controller_configuration.inventory_sources : Validating arguments against arg spec 'main' - An Ansible Role to create inventory sources on Ansible Controller.] *****************************************************************************************************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [infra.controller_configuration.inventory_sources : Managing Inventory Sources] ********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The conditional check '__controller_source_item.source != \"constructed\"' failed. The error was: error while evaluating conditional (__controller_source_item.source != \"constructed\"): 'dict object' has no attribute 'source'. 'dict object' has no attribute 'source'\n\nThe error appears to be in '/home/rabel/.ansible/collections/ansible_collections/infra/controller_configuration/roles/inventory_sources/tasks/main.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: \"Managing Inventory Sources\"\n  ^ here\n"}

PLAY RECAP **********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0


```

Yours
David
