### ISSUE TITLE
Web UI errors when loading workflow node without skip_tags

### ISSUE THREAD

**Issue by kbreit** [redhat-cop/automate_tower_genie_collections#746]
# Summary

I am creating workflow templates and it executes successfully. However, when I load the workflow visualizer and click the "i" button to see information about the node it fails with an error of `TypeError: u.skip_tags is null`. My node is defined as the following:

```
     - identifier: "New VM"
        workflow_job_template: "Create VM"
        unified_job_template: "Create VM"
        organization: "Default"
        all_parents_must_converge: "False"
        inventory: localhost
        job_tags: vm
        success_nodes:
        - "Refresh Inventory"
```

# Issue Type

- Bug Report

# Ansible, Collection, Controller details

```console (paste below)
ansible --version
ansible [core 2.15.6]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.18 (main, Sep  7 2023, 00:00:00) [GCC 11.4.1 20230605 (Red Hat 11.4.1-2)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
# /usr/share/ansible/collections/ansible_collections
Collection                     Version
------------------------------ -----------
ansible.posix                  1.5.4
ansible.utils                  2.11.0
awx.awx                        23.3.1
community.general              8.0.2
galaxy.galaxy                  1.1.1-devel
infra.controller_configuration 2.5.2
ansible-galaxy collection list

Controller version
4.4.8
```

- ansible installation method: EE

# OS / ENVIRONMENT

# Desired Behavior

I'd expect the collection to properly handle the situation where skip_tags aren't provided.

# Actual Behavior

It executes successfully but because skip_tags is null, it's failing in the web UI.

**Comment by ivarmu** [comment]
I've tried to reproduce the problem, with Controller 4.4.4 and 4.5.0, and all is working fine here, so maybe it's not related to the way of the Nodes creation. If you create the same workflow through the WUI... do you get the same behaviour?

**Comment by kbreit-insight** [comment]
I created a new workflow in the WUI and it worked fine. Here's the output from the filetree_create role.

```
controller_workflows:
  - name: "Test"
    description: ""
    organization: "Default"
    state: "present"
    simplified_workflow_nodes:
      - identifier: "a1f3bcaa-4b5e-4f8e-85ad-e20a875547ee"
        workflow_job_template: "Test"
        unified_job_template: "Conway"
        organization: "Default"
        all_parents_must_converge: "False"
      - identifier: "9580173a-dfcc-420e-9622-8562e88e9f3b"
        workflow_job_template: "Test"
        unified_job_template: "New VM"
        organization: "Default"
        all_parents_must_converge: "False"
        success_nodes:
          - a1f3bcaa-4b5e-4f8e-85ad-e20a875547ee
    survey_enabled: "False"
    ask_variables_on_launch: "False"
    allow_simultaneous: "False"
    scm_branch: ""
    webhook_service: ""
    survey_enabled: False
    survey_spec: {}

```
