### ISSUE TITLE
controller_credentials password field-use another credential.

### ISSUE THREAD

**Issue by mondherGL** [redhat-cop/automate_tower_genie_collections#820]
Hello ,

is it possible to refer another credential on password filed with controller_credentials ?
for example i have created credential **CyberArk** with type CyberArk Central Credential Provider Lookup i want to use it to create another credential like this :

controller_credentials:
  - name: "Machine Credentials Example"
    description: "Machine Credentials Example"
    credential_type: "Machine"
    organization: "ExampleOrg"
    inputs:
      username: "user-ansible"
      password: **CyberArk**

Thank you in advance for your response, 
Mondher Khaskhoussi

**Comment by djdanielsson** [comment]
that is not how lookups work, you would create credential_input_source which would look something like:

```  
- source_credential: cyberark
    target_credential: gitlab
    input_field_name: password
    metadata:
      object_query: "Safe=MY_SAFE;Object=AWX-user"
      object_query_format: "Exact"
    description: Fill the gitlab credential from CyberArk
```

see the role for more details https://github.com/redhat-cop/controller_configuration/tree/devel/roles/credential_input_sources
