### ISSUE TITLE
Change default value for tags in workflows

### ISSUE THREAD

**Issue by ephracis** [redhat-cop/automate_tower_genie_collections#824]
# Summary

When enforcing defaults (ie `controller_configuration_workflows_enforce_defaults` is set to `true`), the value for `skip_tags` and `job_tags` are set to empty strings. This causes these values to override whatever value is set on the individual nodes. The correct default value should instead be null as that value will not take precedence over the values on the nodes in the workflow.

# Issue Type

- Bug Report

# Ansible, Collection, Controller details

```console (paste below)
ansible --version
ansible [core 2.15.5]
  config file = None
  configured module search path = ['/Users/christoffer/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/christoffer/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.11.6 (main, Oct  2 2023, 13:45:54) [Clang 15.0.0 (clang-1500.0.40.1)] (/opt/homebrew/opt/python@3.11/bin/python3.11)
  jinja version = 3.0.3
  libyaml = True

ansible-galaxy collection list
Collection              Version
----------------------- -------
ansible.controller 4.5.1
ansible.content_builder 0.0.0
ansible.netcommon       6.0.0
ansible.utils           3.0.0
azure.azcollection      1.18.1
community.general       7.1.0
infra.controller_configuration 2.3.0

Controller version
4.5.6
```

- ansible installation method: EE

# Desired Behavior

When enforcing defaults it should be possible to assign different tags on different nodes in workflows. This means that `job_tags` in the workflow must be set to null.

# Actual Behavior

When enforcing defaults, the value for `job_tags` in workflows are set to an empty string. This overrides whatever is set on the individual nodes in the workflow and causes them to run without any value for `job_tags`.

# STEPS TO REPRODUCE

```yaml
controller_configuration_enforce_defaults: true
controller_workflows:
- name: My Workflow
  simplified_workflow_nodes:
    - identifier: My Node
      unified_job_template: Some Template With Prompt For Tags
      job_tags: ignored_tag
```
