### ISSUE TITLE
State Exists

### ISSUE THREAD

**Issue by willtome** [redhat-cop/automate_tower_genie_collections#839]
https://github.com/redhat-cop/controller_configuration/blob/09d923968b650e7ab7747f8c0177a55055ab7484/roles/global_vars/defaults/main.yml#L3

The credential module now features a new state called `exists`. This state is not present in the global_vars file referenced in this issue and needs to be added or state validation fails. The variable should be changed to

```
operation_translate:
    present:
      verb: "Create/Update"
      action: "creation"
    absent:
      verb: "Remove"
      action: "deletion"
    exists:
      verb: "Already Exists"
      action: "exists"
```

@ivarmu 
cc: @djdanielsson
