### ISSUE TITLE
Missing Export of 'input_inventories' in 'filetree-create' Role

### ISSUE THREAD

**Issue by silvinux** [redhat-cop/automate_tower_genie_collections#841]
# Summary

The parameter input_inventories and its corresponding values are not being exported into the constructed inventories as expected.

# Issue Type

- Bug Report

# Ansible, Collection, Controller details

```console (paste below)
ansible --version 2.16.5

ansible-galaxy collection list

Collection                               Version
---------------------------------------- -------
infra.aap_utilities                      2.5.0  
infra.ah_configuration                   2.0.6  
infra.controller_configuration           2.7.1  
infra.eda_configuration                  1.1.0  
infra.ee_utilities                       3.1.3  

Controller version 4.5

```

# Actual Behavior

```
---
controller_inventories:
  - name: "Inventory-Constructed-Instances-001"
    description: ""
    organization: "Default"
    kind: "constructed"
    prevent_instance_group_fallback: False
    source_vars:
      groups:
        target_group: group_names is search("ins001") or group_names is search("web")
      plugin: constructed
      strict: true

    update_cache_timeout: 0
    limit: "target_group"
    verbosity: 0
    variables:
      {}
...
```

# STEPS TO REPRODUCE

1.- Create an constructed inventory with at least one inventory related.
2.- Export with role filetree-create:
```
ansible-navigator run playbooks/config-controller-export.yaml -i localhost -m stdout --eei quay.io/automationiberia/casc/ee-casc:latest --eev /tmp/:/tmp/ -e @vars/vault-controller.yaml
```

# Expected Behavior
```
---
controller_inventories:
  - name: "Inventory-Constructed-Instances-001"
    description: ""
    organization: "Default"
    kind: "constructed"
    prevent_instance_group_fallback: False
    source_vars:
      groups:
        target_group: group_names is search("ins001") or group_names is search("web")
      plugin: constructed
      strict: true
    input_inventories:
      - "West Datacenter"
      - "East Datacenter"
    update_cache_timeout: 0
    limit: "target_group"
    verbosity: 0
    variables:
      {}
...
```
