### ISSUE TITLE
Dispatcher omitting EDA roles

### ISSUE THREAD

**Issue by zjleblanc** [redhat-cop/automate_tower_genie_collections#987]
## Summary

The dispatcher role is missing an entry for the `eda_event_streams` and `eda_credential_types` role to configure EDA as code.

## Issue Type

- Bug Report

## Ansible, Collection, Controller details

```console (paste below)
ansible --version
ansible [core 2.16.3]

ansible-galaxy collection list
Collection                               Version
---------------------------------------- -------
amazon.aws                               8.2.1  
ansible.controller                       4.6.2  
ansible.eda                              2.2.0  
ansible.hub                              1.0.0  
ansible.netcommon                        5.2.0  
ansible.platform                         2.5.3  
ansible.posix                            1.5.4  
ansible.scm                              1.2.1  
ansible.utils                            2.11.0 
ansible.windows                          1.13.0 
infra.aap_configuration                  3.1.0  
infra.ah_configuration                   2.0.4  
infra.controller_configuration           2.11.0 
infra.eda_configuration                  1.1.0  
infra.ee_utilities                       3.0.0  
redhat.openshift                         2.3.0  
redhat.rhel_system_roles                 1.21.2 
redhat_cop.controller_configuration      2.3.0  

Controller version
4.6.2
Event Driven Automation Version
1.1.2
Automation Hub Version
4.10.1
```

- ansible installation method: pip

## OS / ENVIRONMENT

MacOS Sequoia 15.1.1

## Desired Behavior

boths roles should be called from dispatcher if relevant variables are defined

## Actual Behavior

neither role is called from dispatcher when relevant variables are defined

Please give some details of what is actually happening.
Include a [minimum complete verifiable example] with:
- define the eda_event_streams variable
- define the eda_credential_types variable
- ensure the vars are loaded
- call `infra.aap_configuration.dispatch`
- observe the role is never dispatched

This is due to the missing entry here:
https://github.com/redhat-cop/infra.aap_configuration/blob/05b830566dcc61b49195ee27848426b7a0a12574/roles/dispatch/defaults/main.yml#L175

```console (error)
No error - role is never called
```

## STEPS TO REPRODUCE

```yaml (playbook/task)
---
- name: Apply EDA Configuration-as-code
  hosts: localhost
  gather_facts: false
  become: false

  vars_files:
    - vars/eda_secrets.yml

  tasks:
    - name: Include EDA configuration files
      tags: always
      ansible.builtin.include_vars:
        dir: eda

    - name: Call dispatch role for EDA configuration
      tags: always
      ansible.builtin.include_role:
        name: infra.aap_configuration.dispatch
...
```

```yaml (config/list/array/variables)
---
eda_event_streams:
  - name: Dynatrace Event Stream
    credential_name: Dynatrace Credential
    organization: Default
    forward_events: true
eda_credential_types:
  - name: REST API Credential
    description: REST API Credential
    inputs:
      fields:
        - type: string
          id: rest_username
          label: REST Username
        - secret: true
          type: string
          id: rest_password
          label: REST Password
      required:
        - rest_username
        - rest_password
    injectors:
      extra_vars:
        rest_password: !unsafe "{{ rest_password }}"
        rest_username: !unsafe "{{ rest_username }}"
...
```
